### ISSUE TITLE
Will NSpec users be forced to run tests through a custom Program.cs?

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#105]
@amirrajan , recently in several issues (mainly those somehow related to loading the assembly under test at runtime) there's a closing comment similar to this:

> require devs to build their own Program.cs, like this: 
> &lt;...code sample follows...&gt;

A couple of questions come to my mind:

1. Does that mean that one is *forced* to run them from the console? 
1. Does that mean that one cannot run them in VS (through adapters)?
1. What does this mean in general, from NSpec user point of view?

Thanks

**Comment by amirrajan** [comment]
>Recently in several issues (mainly those somehow related to loading the assembly under test at runtime)

Rolling your own console app should resolve any App Domain/config file issues. A lot of the referencing problems go away when the developer owns the execution process all together.

>Does that mean that one is forced to run them from the console

Well the console app is one way to run them. If someone wanted to, they could use the concepts from the console app to create a visual test runner.

>Does that mean that one cannot run them in VS (through adapters)?

You can still funnel them through TDD.net/NUnitRunner/etc by embedding the same code into the test method (similar to `DebuggerShim.cs`). Having a console app imho makes testing much more approachable to new comers: "Just create a console app. Past this code in there. Put your breakpoint. Hit F5."

>What does this mean in general, from NSpec user point of view?

NSpec.exe will still ship under tools. But the documentation will state that developers should build their own Program.cs.

A couple of reasons why I feel this is the best direction.

1. App Domain and Configuration issues go away.
2. Encourages developer to customize their own console apps to do crazy things like run tests in parallel or execute tests in multiple dll's.
3. Be editor agnostic (mono and DNXCore prep).
4. App Domain and Configuration issues go away.
5. App Domain and Configuration issues go away.

I want to be very careful in making this transition of course. The dog fooding I've done so far has been going well.

**Comment by BrainCrumbz** [comment]
Uhm. Not totally convinced, to tell the truth. I agree on giving this one more *tool* in developer's hand, so that they can choose what suit them better. But I don't like the idea of removing another tool from their hands (i.e. the VS Test Runner)

On AppDomain & Configuration issues, couldn't we try to solve those? There are other testing frameworks (like NUnit) that need to create separate AppDomains to load the DLL with tests, probably they faced similar issues, still they're widely used so I guess those issue have been solved. I mean, it's not the first case of creating AppDomains and getting them right.

If you want to make the tests available to some kind of test runner (be it TDD.net, NUnitRunner, or Visual Studio Test Adapter), then you're back again with those AppDomain issues, as I guess they need to load tests from an external binary, whether it has a `Program.cs` or not, and when loading that binary they have to take care about configuration anyway.

Also consider that, being .NET developers, I expect that many NSpec users work a lot with Visual Studio (on Windows). Of course things can change in the future, with MS DNX opening to *nix and Mac. But still, it seems reasonable to think that a big chunk of those developers for now is on VS and there will be for some time. As a matter of fact, NUnit as well as other test frameworks offer a VS Test Runner, besides possibly other runners (TDD.Net, Reshaper, console, their own windowed runner, ...). 
When you say that the dog fooding done is going well, I invite you to think that you're still missing a consistent part of "another way of eating" :smiley_cat: which is the one through VS. Maybe I'm biased, but historically VS has put a lot of effort on developer ease of use. When a newcomer arrives, steps are: "Just create a ClassLibrary app. ~~Paste this code in there.~~ Put your breakpoint. Hit F5." For a classic .NET developer, running tests from a console might be the exception, not the rule.

Maybe, in order to better split responsibilities (and hence avoid many issues), one way could be to completely split NSpec (the framework) project from NSpecRunner (the console runner). Then, document as a preferred and supported implementation the one having a test **executable** (instead of DLL), with its own Program.cs, etc. Possibly, document as an alternative the console runner you provide as a tool, as well as the classic DLL way in an IDE, but warn about issues related to AppDomains.

Still, I'd be very cautious in choosing a path for NSpec (the no-DLL way) that in classic .NET world seems rather peculiar. I'd leave the choice to embrace both, so to be open to both Windows and non-Windows .NET worlds.

*Side note*: as you know I just started with an alternative VS Test Adapter for NSpec as a part-time thing. Please, look at that as a proof (and not a cause) of my reasoning: as much as there exists a console test runner, and also an existing VS Test Runner which lacks something here and there, I still prefer to put my own effort and try to create a working, fast, up-to-date VS runner.

**Comment by amirrajan** [comment]
I'll reply in full when I get the chance. But I definitely want to make sure both stories are handled correctly (and are first class). So I wont be taking anything away.

App Domain stuff is maddeningly complicated. See: https://github.com/fixie/fixie/tree/master/src/Fixie/Execution

**Comment by BrainCrumbz** [comment]
Yes ... that was a little bit too long, sorry about that. And yes, AppDomain stuff is complicated, we've also read about Fixie creator mentioning that, and you guys comments on their project.

**Comment by amirrajan** [comment]
>Uhm. Not totally convinced, to tell the truth. I agree on giving this one more tool in developer's hand, so that they can choose what suit them better. But I don't like the idea of removing another tool from their hands (i.e. the VS Test Runner)

Agreed. I won't be removing the runner.

>On AppDomain & Configuration issues, couldn't we try to solve those?

_Runs away screaming._

>If you want to make the tests available to some kind of test runner (be it TDD.net, NUnitRunner, or Visual Studio Test Adapter), then you're back again with those AppDomain issues.

Dammit, you're right. _Runs away screaming._

>When a newcomer arrives, steps are: "Just create a ClassLibrary app. Paste this code in there. Put your breakpoint. Hit F5." For a classic .NET developer, running tests from a console might be the exception, not the rule.

I wasn't aware that the built in VS test runner supports NUnit/XUnit by default, so that's a good point. I'll probably update the NSpec package to include a Program.cs so there is no copy and paste needed... just need to find a good way to support the class library approach too (again, I'm being very cautious with this change).

In my past experience with VS, you had to choose MSTest if you wanted to use the built in runner. Otherwise you'd have to install TDD.net/ReSharper (getting paid licenses in a corporate environment for these tools is a lot of red tape).

>Maybe, in order to better split responsibilities (and hence avoid many issues), one way could be to completely split NSpec (the framework) project from NSpecRunner (the console runner). 

Naw, just simpler to keep one project and one Nuget command (if that's alright with you).

>Still, I'd be very cautious in choosing a path for NSpec (the no-DLL way) that in classic .NET world seems rather peculiar.

May be worth noting that the classic .Net world won't even consider NSpec as a viable option (because it isn't MSTest/XUnit/NUnit). Most of the developers that use NSpec have had experience with RSpec/Jasmin/Mocha and are familiar with console runners and editor agnostic solutions. At the end of the day I want to cater to those that use NSpec (just a more focused target). And yes, being very cautious with this proposal.

>Side note: as you know I just started with an alternative VS Test Adapter for NSpec as a part-time thing. 

You rock. :-)

**Comment by BrainCrumbz** [comment]
Thanks for taking the time to answer. 

Not going bit by bit here, but very good point about meeting NSpec users coming from RSpec/Mocha/Jasmine experience, which maybe are not so used (yet :smile: ) to Visual Studio IDE. We were already on VS but we liked the Mocha-way of testing when doing RIA web app works, so when back to .NET we looked for similar ways of testing and that's why we choose NSpec. So there's still a lot of hope for classic .NET adopters :smile: 

On VS testing experience, things have drastically improved since then (we remember NUnit windowed runner ...). Of course there are many people out there using Resharper plugins as well as other means to run tests while they're coding. We hope we can keep the door open to more ways to do that!

**Comment by amirrajan** [comment]
That sounds good. Personally (which most definitely doesn't represent the majority), using specwatchr/sidekick plus the `focus` tag gets me going. 

Whenever I need to debug, I ask myself why the `ToString()` for an object doesn't give me the visibility I need (at which point I override `ToString` to give me more helpful information and stick to `Console.WriteLine()`). I also think about why I don't have debug/info/error logs I can tail (at which point I think about adding those kind of log files). Sometimes you need to debug at which point I admit defeat and add `System.Diagnostics.Debugger.Launch()` and start up Visual Studio. This is of course philosophical... so feel free to ignore my rants :-)

**Comment by BrainCrumbz** [comment]
Those are exactly the same steps we take, apart from hitting F9 (or clicking in the gutter) instead of adding `System.Diagnostics.Debugger.Launch()`

**Comment by amirrajan** [comment]
Wouldn't you do the same if it were a console app?

**Comment by BrainCrumbz** [comment]
Well, not really I guess. Just because you're asking: The whole point of working in an IDE is the **I**(ntegrated). Without leaving the editor one can see console output messages if needed, as well as running tests, as well as... 

And on running tests in particular, one can run them all, or group them by several criteria, or just CTRL-select some of them at will and run. That seems to me more powerful than going back and forward between our *actual* code and console `Program.cs` just to change a tag or other mean of selecting tests. When looking at test details, you can browse straight to the failing testcase or offendine line throwing exception.

![vs test runner](https://cloud.githubusercontent.com/assets/3185573/12364318/2c661794-bbce-11e5-8e2e-1d55d1a3160c.png)

**Comment by amirrajan** [comment]
Yep. All fair points ^

**Comment by BennieCopeland** [comment]
I'll throw in my two cents. I personally love the console app way. Once I discovered it, I embraced it whole heartily. I have several reasons why.

1. One is that for some unknown reason, the NSpec Visual Studio runner was not working for me in Visual Studio 2015 Community. Visual Studio would just crash on me.
2. Additionally, I love that I can just add a breakpoint and hit F5 instead of  `System.Diagnostics.Debugger.Launch()`. And once I found the `focus` tag while diving through the source ::cough:: document it ::cough::, it just became that much better.
3. I have a powershell script to run the tests with OpenCover and generate a report. Before, with the nspec console runner, if the nuget package got updated, I would need to change the script to point to the new location. Now, no change is needed.

The only thing I would like to do that I haven't figured out yet, is have all my test projects as DLL's and a single console project that runs them all as one big test group. As it is now, I have four test console apps that get ran individually. My reason for wanting this is so that when I am looking at the output, I have a single spot to see the passing and failed counts. It will also help me not forget to remove a `focus` tag.

**Comment by amirrajan** [comment]
@BennieCopeland  +1 on all you said. Here is a gist that may help you out: https://gist.github.com/amirrajan/7ee4777788e6a5d76fee

I need to create a cleaner api, but essentially you create an array of all types you want to test and then send it through.

**Comment by BennieCopeland** [comment]
@amirrajan So that got me part of the way there. The `GetExecutingAssembly` didn't work because it only gets the console project assembly and not the referenced assemblies that contain the actual specs. I tried `GetExecutingAssembly().GetReferencedAssemblies()` but that only gets the assemblies that the console app actually uses and not just references. What I ended up doing that worked is I replaced this
```c#
var types = Assembly.GetExecutingAssembly().GetTypes();
```
with this
```c#
string[] assemblies =
{
    "Test.Assembly1",
    "Test.Assembly2",
    "Test.Assembly3",
    "Test.Assembly4"
};

Type[] types = assemblies
    .Select(x => Assembly.Load(x))
    .SelectMany(x => x.GetTypes())
    .ToArray();
```

This works and pulls in all the specs from across all four assemblies and runs them. The only issue now is that it doesn't obey the `focus` tag.

**Comment by BennieCopeland** [comment]
WOOT. I just tested, and I can keep the test projects as console projects while STILL referencing them and loading them with the code above. So now, I can use the `focus` tag while running a single test project which also keeps me in my workflow of setting the tag and hitting F5 instead of needing to jump over to the Test.Runner project to hit F5.

**Comment by BrainCrumbz** [comment]
@BennieCopeland on the NSpec VS runner, we're working on that, with another runner, so please stay tuned... hoping that one will not crash as well :smile: 

While having a VS Runner available, in order to debug a testcase what I'd do is put a breakpoint on the interested line and run a single testcase (or more) from Test Explorer window like so:

![test explorer debug](https://cloud.githubusercontent.com/assets/3185573/12445669/f74d64fe-bf65-11e5-909f-cfc2ab6fb158.png)

All: there's something not clear: when you start loading other assemblies at runtime, aren't you back on square one with the same issues that another test runner would meet? E.g. if each *external* assembly loaded at runtime has its own peculiar `.config` file, with e.g. its own binding redirects, don't you end up with those AppDomain and configuration problems?

**Comment by BennieCopeland** [comment]
@BrainCrumbz That will be nice if it works. I always had to add `System.Diagnostics.Debugger.Launch()` to debug on a line.

I did run into an issue when I created the console app where I was missing some connection strings that were in the DLL app.config. I just copied those over and it worked. I think it is similar to how NUnit has it's own .config file for its test runner.

**Comment by BrainCrumbz** [comment]
> I did run into an issue when I created ...

I think that is exactly the type of AppDomain & config problems that the *simple* console approach is trying to avoid in the first place. Connection strings and application settings are just one example of *things* that are set in config files. 

If you start copying those between *main* project and test project, you have duplication and a number of issues may arise with time (e.g. "hey Joe, did you remember to copy changed config to the test project as well?"). Multiply that by the number of DLL that you have to test. When you also *merge* a number of DLL to test into one console runner, you could also have issues with overlapping, like app settings with the same name, not to talk about different binding redirects that simply cannot coexist in the same config file.

All this is just to suggest to be careful going down that route.

**Comment by amirrajan** [comment]
Yep. All very good points @BrainCrumbz.

So to directly address this issue. **It was really heavy handed to say that the next NSpec release (specifically the website documentation) will force people to create their own console app. Both options (nspec runner, and roll your own) will be documented.**

I just hope that someone can help me with the (deeper) AppDomain issues. The current runner handles for config files, but I'm sure that we are missing some other scenarios.

Is it alright to close this? @BrainCrumbz @BennieCopeland

**Comment by BrainCrumbz** [comment]
Alright for us. On AppDomain issues, we'll be around for those. It might as well be that we'll face those issues on the VS adapter we're working at.

**Comment by amirrajan** [comment]
Cool cool. I'll consider it closed. My apologies for being crazy.

**Comment by BrainCrumbz** [comment]
:+1: every now and then is good to spice up discussion and see what comes out! :smiling_imp:

**Comment by amirrajan** [comment]
You are as evil as the AppDomain, sir.
