### ISSUE TITLE
Is there any interest in making shared contexts a feature?

### ISSUE THREAD

**Issue by BennieCopeland** [mattflo/NSpec#107]
I know I can create a base class and inherit from it, but I am looking at more the rspec feature of `it_behaves_like`. I've got a half baked implementation that I think could work. The only piece I don't have is how the specs are actually discovered. The way it will be used is like the following:

```c#
// MyObj_specs.cs
context["some context"] = () =>
{
    MyObj obj = null;

    beforeEach = () => { obj = new MyObj(); }

    it_behaves_like["a shared context"] = with(() => { obj });
};

// shared_specs.cs
class shared_specs : nspec_shared
{
    void MySharedSpecs()
    {
        context["a shared context"] = () =>
        {
            it["will do thing A"] = (ctx) =>
            {
                ctx.Get<MyObj>("obj").SomeProperty.Should().Be("1");
            };
        };
    }
}
```

The `it_behaves_like`s type is similar to an `ActionRegister` except it takes a `Func<SharedContext>` instead of an `Action`. The `SharedContext` class is basically a wrapper around a dictionary. The `with` function takes an anonymous object, iterates over the properties, and creates a `SharedContext` from it. The `it_behaves_like` maps to a new function called `AddSharedExample` that will need to go out and find the shared specs and add them to the current class's `context/it`.

I've got some thoughts on shared context discovery like using a lazily loaded static Dictionary to store the `contexts` and `it`s. Maybe force a specific `shared_specs` class name or discover at runtime all classes inherited from `nspec_shared`. What are your guys thoughts?

**Comment by amirrajan** [comment]
Create an `abstract` class to do a behaves like scenario :-) 

Here is an example: https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicModel/describe_Validation/exclusion.cs
