### ISSUE TITLE
NSpec.VsAdapter: initial tests on real projects

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#110]
@amirrajan if/when you have the chance, it would be great if you could give a go at our VS test adapter for NSpec, [NSpec.VsAdapter](https://github.com/BrainCrumbz/NSpec.VsAdapter).

We ran it on a couple of real projects (beside dummy projects & unit/integration tests, of course) and it seems to be fine. It is much quicker than another NSpec Visual Studio test runner we tried in the past.

Instructions, if needed, are in [readme#Contributing](https://github.com/BrainCrumbz/NSpec.VsAdapter#contributing): it is just a matter of setting the startup project & pressing F5 to run an experimental VS instance (so not to interfere with your *official* working environment).

Maybe you didn't use Visual Studio a lot recently, but maybe this will tempt you to do so :smiley_cat:

**Comment by amirrajan** [comment]
You will have to pull emacs out of my cold dying hands.

I'll give VS a shot this weekend though ^_^

**Comment by BrainCrumbz** [comment]
:smile: 
...only VS2013 for now, [sadly](https://github.com/BrainCrumbz/NSpec.VsAdapter/issues/4)
Thanks a lot
