### ISSUE TITLE
Add minimal docs on async support in readme

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#113]
There's been at least a couple of issues opened on NSpec misbehaving in async scenarios, only to find out that people were using the non-async API. This makes them (and us) loose time for something that could be documented even in a tiny tiny way, waiting for a proper documentation available on web site after its major overhaul.

I'd suggest to take the cue from comments given in these issues: #109 and #112 (please add more if available, those are the ones I remember) and use them to put up a small dedicated section in main README.md.

@amirrajan what do you think?

**Comment by amirrajan** [comment]
Is there any way to throw an exception when `async` is enabled? Meaning is it safe to assume that once you go async, any  nested tests must be async? If that's the case, the nspec instance could have a stateful flag that throws if a sync method is used?

**Comment by amirrajan** [comment]
And yes I still need to update the website T_T.

**Comment by BrainCrumbz** [comment]
Sorry, I did not get what you wrote before. Just to share common understanding: as of now exceptions Vs async work fine, that is: exception is thrown from `nspec` async hooks, is collected by library and correctly reported to unit test code.

So, at the moment, I only see the need to explain that there exist an async part of the library.

**Comment by BrainCrumbz** [comment]
If, by chance, you are referring to something like "detect when an async lambda is assigned to `it` or `before`", I think the answer is no. On top of my head, I don't remember the details now, but somehow it's like if by the time the async lambda gets assigned to a non-async hook, the library looses the ability to detect whether it was async or not in the first place.

**Comment by amirrajan** [comment]
>If, by chance, you are referring to something like "detect when an async lambda is assigned to it or before"

Yep! That's what I mean!

>I think the answer is no. 

Way to bust my bubble :-P

Could we update the property setter [here](https://github.com/mattflo/NSpec/blob/master/NSpec/nspec.cs#L147) that sets a flag such that any subsequent calls to non async properties throw an exception?

**Comment by BrainCrumbz** [comment]
I think I got what you're looking for, but I don't understand how it can help, sorry. I'll try to recap here, hopefully to have a common starting point. If in the same test class/context you use both sync and async hooks (each one correctly), the test all in all is correct as well:

~~~c#
// ...
  it["does something sync"] = () => doesSomething();
  itAsync["does something async"] = async () => doesSomethingAsync();
// ..
~~~

I think there are some cases where test cannot mix both sync and async hooks, don't remember if it's `before` or `after`, but those cases should be detected by NSpec at runtime and flagged as errors.

The problem NSpec users seem to encounter often is to assign a classic sync hook to run async code:

~~~c#
// ...
  it["does something async"] = async () => doesSomethingAsync();
// ..
~~~

This is basically similar to running an `async void` function, there's no way to wait and resume after it completes, so people find an unexpected behaviour. And I recall of no way to detect this from within NSpec sync hook when it receives the value. 

How does that flag help in this case?

**Comment by amirrajan** [comment]
Gotcha >_<

**Comment by BrainCrumbz** [comment]
Not happy about it, but that's it :O

**Comment by amirrajan** [comment]
Could we blindly `await` everything  that's passed into `it` (inside the internals of NSpec)? Too invasive? Is that even possible?

**Comment by BrainCrumbz** [comment]
Interesting. Don't know if that's possible: at the moment 

1. `itAsync["..."]` can *receive* a `Func<Task>`, 
1. `it["..."]` can *receive* an `Action`

But the two of them have different possibilities as to what can be converted/ assigned to what:

![sync-vs-async-expr](https://cloud.githubusercontent.com/assets/3185573/14281204/01300c48-fb38-11e5-83c8-575b7896c47a.png)

In order to `await` everything they should all be *converted* to `Func<Task>`, but this seems not possible. On the other hand, if everything is converted to `Action`, if I remember correctly you loose the chance to `await` them, and there's no way to recover that (so to say).

**Comment by amirrajan** [comment]
... yep, I think you're right... grr...

**Comment by amirrajan** [comment]
This seems to work

```
        static bool IsAsync(Action action)
        {
            return action.Method.IsDefined(typeof(AsyncStateMachineAttribute),
                                           false);
        }
```

So inside of `NSpec/Domain/ActionRegister.cs` the `Action this[string key]` could throw an exception?

**Comment by BrainCrumbz** [comment]
That's a great thing to know. Earlier I was inspecting the resulting `Action`s in debug, looking for some hint that could help distinguish `syncAsAction` from `asyncAsAction`, and I could not find any.

OT: I don't know how's that, but in the past I came through that question: just found my vote on a comment O.o

**Comment by BrainCrumbz** [comment]
Working at a PR for this. BTW, we already introduced a working method checking for that (!!): https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/Extensions/DomainExtensions.cs#L85

**Comment by BrainCrumbz** [comment]
@amirrajan please have a look at PR #115 , if it's ok for you as well we can merge that.

**Comment by BrainCrumbz** [comment]
@amirrajan this other PR is for the mentioned documentation on async.
