### ISSUE TITLE
Error when spec and parent both have before_each but one is async and the other isn't

### ISSUE THREAD

**Issue by tl24** [mattflo/NSpec#118]
I'm seeing an issue where I have a spec that has a before_each and the parent also has a before_each .

Example:

```
internal abstract class Parent : nspec {
    private void before_each() {
       // do stuff
    }
}

internal class Test : Parent {
    private async Task before_each() {
       // do async stuff
    }
}
```

I get the following error:
Context Failure: A single class cannot have both a sync and an async class-level 'before_each' set, please pick one of the two

I would expect this to work since the before_each's are on different classes.

**Comment by BrainCrumbz** [comment]
Hi there, thanks for your feedback.

I had a quick look at the code and I agree with you: the error message does not correctly match with that scenario. 

What are you aiming at? If that can be useful to you, one create and nest *contexts* below the class level, as in the following sample. There you can mix the same sync/async test hooks (e.g. `before`) by placing them at different nesting levels:

```c#
class describe_my_entity : nspec 
{
  void when_some_use_case()
  {
    context["given some scenario"] = () => 
    {
      before = () => { /* setup scenario */ };
      // ...
      context["given some sub-scenario"] = () => 
      {
        beforeAsync = async () => { /* setup async sub-scenario */ };
        // ...
      };
    };
  }
}
```

**Comment by BrainCrumbz** [comment]
Speaking about the internals, here's what currently happens in the library, when working with test hooks set directly at class-level (like those `void before_each()` and `async Task before_each()`):

1. the class works as a *context*, similar to those `context["..."]`
1. for that class, all its inheritance chain is pulled
1. all `void before_each()` methods found in that class and its ancestors, are taken as a *single* operation (of course, to be ran in proper order). Same thing happens for all `async Task before_each()` methods found.
1. at this point, as you can guess, the inheritance chain has been flatted out. So, as long as you have 1 for each type somewhere in your chain, the problem will show up.

**Comment by tl24** [comment]
We have several tests of a similar style, so I created a base class for them.  The setup of the base class didn't need to be async, but the actual test class needed to do some async setup.  I worked around it by making the base class before_each async as well even though it didn't need to be.  I would think the error message should only show up when you have async and sync at the same level in the class hierarchy.

**Comment by BrainCrumbz** [comment]
I see. As it is, the message does not match the actual logic, that's for sure. I'm thinking about your scenario, and it starts to makes sense that one could mix & match, for the same test hook, at different levels within the hierarchy...

**Comment by amirrajan** [comment]
Keep in mind that there is a difference between a base class and an `abstact` base class. @tl24, could you remove the abstract and see if it runs as expected?

**Comment by BrainCrumbz** [comment]
Is there a doc or piece of test code showing the different behaviour for a concrete Vs abstract base class?

**Comment by amirrajan** [comment]
https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_RunningSpecs/describe_abstract_class_execution_order.cs#L9

**Comment by amirrajan** [comment]
This is probably a better example: https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicModel/describe_Validation/acceptance.cs#L6

**Comment by BrainCrumbz** [comment]
uhm ... sorry, not totally clear what changes w.r.t deriving from a concrete base class.

**Comment by amirrajan** [comment]
Abstract classes act like "behaves like". so a structure like this:

```
abstract_class
  - it_1
  - it_2
  - it_3
  
derived_class_1 : abstract_class
  - it_4
  
derived_class_2 : abstract_class
  - it_5
```

Is equivalent to:

```
derived_class_1 
  - it_1
  - it_2
  - it_3
  - it_4
  
derived_class_2
  - it_1
  - it_2
  - it_3
  - it_5
```

**Comment by BrainCrumbz** [comment]
Thanks for clarifying on the role of abstract class related to testcases (*it_...*). 

Q1: What about test hooks like *before*s, that seems more central to this issue?

Q2: Should we allow in a spec class hierarchy, to mix sync/async hooks when at different levels of the hierarchy? (As in initial OP example)

**Comment by amirrajan** [comment]
Hmm, not sure how having a before in an abstract class, and a before in a derive class will make things behave. I'd assume that both should run, first the abstract, then the derived?

As for async hooks. _Runs and hides_.

**Comment by BrainCrumbz** [comment]
Don't know really, I mean, I did not grasp yet the complete picture of what happens with method-level test hooks, as we don't make extensive use of that in our tests.

On one side, it seems reasonable that those methods should behave like all other methods w.r.t. inheritance, so e.g. a derived class should either `override` or `new` a method declared in base class (whether abstract or concrete).  
Maybe this sounds obvious, but just to be sure: if that's the choice, then the signature among those methods at different levels should not change, so e.g. they all return either `void` (for sync case) or `Task` (for async case).

Does this sound meaningful?

**Comment by amirrajan** [comment]
Thoughts on any of this @tl24?

**Comment by tl24** [comment]
I guess method-level inheritance would be the better option and provide the most control, but that's not how the class-level before/after hooks work currently I don't think.  

We actually don't need this behavior anymore.  I see you made a commit to fix the error message.  So you guys could probably close this unless you want to make a change.
