### ISSUE TITLE
nspec.org broken examples.

### ISSUE THREAD

**Issue by Steinblock** [mattflo/NSpec#120]
I used nspec.org as a reference.

Since a couple of weeks some examples only show `using NSpec;` even the source code does not contain the actual code

```
<p><a name="pending"></a></p>
<div class="zone zone-sub-page-title">
<h1>pending</h1>
</div>
<div id="layout-content" class="group" style="padding-top: 10px;">
<pre id="describe_pending_code" data-timestamp="2016-04-13 07:08:50 -0600" class="brush: csharp;">using NSpec;
</pre>
```

On 16.04.18 the site looked correct.

http://web.archive.org/web/20160403115830/http://nspec.org/

**Comment by amirrajan** [comment]
Dammit, I think it's the `/r/n` differences in Mac vs Windows. I'll get this fixed asap.

**Comment by amirrajan** [comment]
Fixed it was an error in my `gsub` and `regex`
