### ISSUE TITLE
Why exceptions in MethodContext.Build are not caught?

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#123]
We noticed a behavior while working at our NSpec VS adapter, with a spec class similar to the following:

```c#
class SomeSpec: nspec
{
  // ...
  void Given_a_method_context()
  {
    // while building some data used in this context, an exception is thrown
    InputData badInput = null;
    FixtureData expected = new FixtureData(badInput);  // <-- Boom
    FixtureData actual = null;

    before = () => { ... };
    act = () => { actual = ... };

    it["Should test actual Vs expected"] = () => actual.Should().Be(expected);
  }
}
```

we noticed that, for interested assembly/binary, the whole discovery phase in our adapter fails (gracefully) with 0 found results for the whole binary, even if only *that* context in *that* class exposed a problem.

The trigger seems to be an exception thrown when running the main body of method context (note: context body, **not** the body of `before`, `act`, ... hooks). In such a scenario:

1. `NSpec.Domain.MethodContext.Build()` catches exception only to [log a message to console](https://github.com/mattflo/NSpec/blob/ec89a44bf89725033d718920d1da02e0ca9bea71/NSpec/Domain/MethodContext.cs#L18) which, incidentally, is not visible when running from within VS test adapter. Then it just throws exception again

1. As there's no other catch, the whole call chain up to `NSpec.Domain.ContextCollection.Build()` fails as well

1. At this point, our adapter had invoked such code remotely so to run on test assembly. Uncaught exception causes a `TargetInvocationException` in adapter code, which gets caught and logged in VS test runner output window. But this also causes the whole test discovery on that assembly to fail.

We were thinking whether there's a way to only make fail a specific context (the one that threw) and its descendants. Any idea? Thanks

**Comment by BrainCrumbz** [comment]
An alternative could be to add a "synthetic" failing expectation mentioning what happened while processing that method context, so the whole process would not fail and NSpec user (whether through runner or what else) would be informed about what has to be fixed.

**Comment by amirrajan** [comment]
The

```
// while building some data used in this context, an exception is thrown
InputData badInput = null;
FixtureData expected = new FixtureData(badInput);  // <-- Boom
FixtureData actual = null;
```
must be wrapped in a `before` or `act` block. There is a pending test to explore the idea of having [bare methods](https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_RunningSpecs/describe_implicit_befores.cs), but it's currently ignored. The challenge here is that NSpec discovers the test structure by invoking all instance methods, and the assumption is that there are no "bare" lines that could through exceptions within the instance methods (ie. only NSpec `it`, `before`, `act`, etc are being set.

Maybe Roslyn will give us the ability to inspect method structures and implicitly create lambdas around bare structures.

**Comment by BrainCrumbz** [comment]
I see. After quite some time using NSpec, we kind of settled on a recurring way of using it: many times, it happens that the meat of the hook is a one-liner, where you just exercise the setup or the expectation.  Apart from that, we just have the actual instantiation of expected and injected values/objects, which we tend to put outside of hooks as taht is "just" setting data, not real action. So for our team bare methods are not really a need. But I see your point.

But when this exception happens, it is quite unfriendly to get what's going on in VS. There's just a test runner that has crashes the test discovery phase, no console log, no specific point in code.

Would you consider a PR for the following feature? 

When a method-level context or a nested context fails during "building" phase, then a syntetic failing expectation is created in its parent context with the exception details, so to show up during "run" phase.  
I'm not totally sure about this feature feasibility, but it sounds like it is doable.

Or as an alternative, what about the following? 

Provide NSpec with an external logger (or formatter, maybe) in order to show errors and messages beside the actual test result. I'm not sure on how many occurrences of writing to console are there now, I think one or two really, but at least it would help in current issue scenario.

What do you think?

**Comment by amirrajan** [comment]
The first option is very doable [this line](https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/ContextBuilder.cs#L59) would have to be wrapped in a `try/catch` and return a predefined NSpec method level example that "just fails" (maybe).

**Comment by BrainCrumbz** [comment]
Cool. This is an excerpt of stack trace when exception was thrown in *bare* instructions within a method-level context:

```
   in MyUnitTestProject.test_SomeClass.Given_method_level_context() in xxxx.cs:row yy
   --- Fine della traccia dello stack dell'eccezione interna ---
   in NSpec.Domain.MethodContext.Build(nspec instance)
   in NSpec.Domain.Context.<>c__DisplayClass12.<Build>b__11(Context c)
   in NSpec.Extensions.Do[T](IEnumerable`1 source, Action`1 action)
   in NSpec.Domain.Context.Build(nspec instance)
   in NSpec.Domain.ClassContext.Build(nspec instance)
   in NSpec.Domain.ContextCollection.<Build>b__6(Context c)
   in NSpec.Extensions.Do[T](IEnumerable`1 source, Action`1 action)
   in NSpec.Domain.ContextCollection.Build()
   in NSpec.VsAdapter.Common.ContextFinder.BuildContextCollection(String binaryPath)
   in NSpec.VsAdapter.Discovery.ExampleFinder.Find(String binaryPath)
   in NSpec.VsAdapter.Discovery.ProxyableTestDiscoverer.Discover(String binaryPath, ICrossDomainLogger logger)
```
and probably the culprit is [here](https://github.com/mattflo/NSpec/blob/ec89a44bf89725033d718920d1da02e0ca9bea71/NSpec/Domain/MethodContext.cs#L14) in `MethodContext`.

The idea would be to work right there with the `nspec instance` in order to add the syntethic example failing with catched exception. Now, is that the right "place" (and instance) where to add the example?

**Comment by amirrajan** [comment]
That looks like the correct place yes. :-)

>PS then we'd do the same for other type of contexts.

Not sure we need to do it for anything that takes in a `() => {}`. Because only "bare" methods are the culprit.

**Comment by BrainCrumbz** [comment]
> Not sure we need to do it for anything that takes in a () => {}. Because only "bare" methods are the culprit.

Totally right. I was thinking about "bare" code run within a sub-context `context[...] = () => { ... }` that is **not** a hook, e.g.:

```c#
// ...
context["Given some sub-context"] = () =>
{
  doSomethingThatThrows();  // <-- This makes the whole sub-context building fail

  before = () => { };

  it[...] = () => { };
};
```

Does that makes sense?

**Comment by BrainCrumbz** [comment]
Here's how it could look like: https://github.com/mattflo/NSpec/tree/feat/bare-code-failing-spec

**Comment by BrainCrumbz** [comment]
One more question: what do you think about proposal in [this comment](https://github.com/mattflo/NSpec/blob/b2e1bf527c79f50e7717088cc08c0c93dde9ed83/NSpec/Domain/MethodContext.cs#L38)?

The idea is to have e.g. some `SpecBareCodeException` with a description that explains what has just happened, as this *synthetic* example is unknown to library user and as such it might come as a surprise. Then, its `InnerException` would hold the actual exception thrown in bare code, so that user can point to it.

**Comment by amirrajan** [comment]
I'd put a recommendation to wrap it in an `act` or `before`. But yea, having something that is more helpful to the user is definitely a plus.

Aside: I generally don't want to encourage bare code (with great power comes great responsibility).

**Comment by BrainCrumbz** [comment]
> I'd put a recommendation to wrap [...]
I did not get that. Could you please elaborate a little bit more?

> Aside: [...]
True. If one starts putting a lot of code outside of hooks, one can end up with a lot of strange issues, maybe also related to test execution order, as it can increase the amount of shared state among tests.

**Comment by BrainCrumbz** [comment]
Ok, PR #125 is there. Feel free to change message shown to user [here](https://github.com/mattflo/NSpec/pull/125/files#diff-41ec5fdc4dc14c22616caf292e5faf6bR11), if you have a more appropriate one. Otherwise we can proceed with check & merge eventually.

Cheers!

**Comment by amirrajan** [comment]
pushed in 1.0.6 🎉
