### ISSUE TITLE
describe_output tests failing after elapsed time reported

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#128]
I noticed by chance that `describe_output` tests now fail, probably after introducing elapsed time in console output. E.g. at `NSpec\NSpecSpecs\describe_output.cs : line 77`

```
Expected string length 161 but was 173. Strings differ at index 84.
  Expected: "...10 degrees\n      should be hot\n    that is 90 degrees\n    ..."
  But was:  "...10 degrees\n      should be hot (7ms)\n    that is 90 degree..."
  ---------------------------------------------^
```

Maybe a suitable regular expression could solve that.

@raghur do you think you can have a look at that?

**Comment by amirrajan** [comment]
yep, fixing that now.

**Comment by amirrajan** [comment]
fixed here: https://github.com/mattflo/NSpec/commit/feb7414201204d9f227038eeeb2ac1b2dab51b34
