### ISSUE TITLE
xitAsync prints an error message

### ISSUE THREAD

**Issue by raghur** [mattflo/NSpec#130]
I have a few async `itAsync` specs that I need to temporarily disable. Intellisense prompts for `xitAsync`
```
 xitAsync["a revoked gateway cannot send events to Azure"] = async () =>
            {
            // spec code
            };
```
the examples are not run - but at the end of the test failures are printed like so

```
**** FAILURES ****

nspec. S03 Gateway Specs. revoking and reregistering gateway. a revoked gateway cannot send events to Azure.
'xit' cannot be set to an async delegate, please use 'xitAsync' instead
```

**Comment by amirrajan** [comment]
Could you provide the surrounding code too? Is there any `before` are `act` still being executed?

**Comment by raghur** [comment]
here's a complete class

```
[Tag("dummy")]
    class Dummy_Specs : nspecbase
    {

        public void describe_scenario()
        {
            it["should run"] = () =>
            {
                5.should_be(5);
            };


            it["takes longer"] = () =>
            {
                Thread.Sleep(1000);
                5.should_be(5);
            };

            xitAsync["a pending spec"] = async () =>
            {
                await Task.Delay(10);
                "Should not be printed".Info();
            };
        }
    }
```

**Comment by BrainCrumbz** [comment]
Will have a look at it in these next days. Thanks for the full class example, that will be the first thing to try!

**Comment by BrainCrumbz** [comment]
.. but from a quick look it seems the problem lies in `Context.HandleSkipped(...)` [here](https://github.com/mattflo/NSpec/blob/c1ef4d5e93ed1b3085620a231b7257cf60875ef0/NSpec/Domain/Context.cs#L403), which considers only a sync example, not an async one.

Will have to also double-check NSpec tests as well, whether this test case is missing or what.

**Comment by BrainCrumbz** [comment]
Hi there. Trying with following spec class and everything seems fine ... which maybe strange after all, but anyway:

```c#
    [Tag("dummy")]
    class Dummy_Specs : nspec
    {
        public void describe_scenario()
        {
            it["should run"] = () =>
            {
                5.Should().Be(5);
            };

            it["takes longer"] = () =>
            {
                Thread.Sleep(1000);
                5.Should().Be(5);
            };

            xitAsync["a pending spec"] = async () =>
            {
                await Task.Delay(10);
                Console.WriteLine("Should not be printed");
            };
        }
    }
```

The differences are:

1. asserting through FluentAssertions, not those helpers deriving from NUnit
1. deriving directly from `nspec`. Not sure what that `nspecbase` does in your case
1. logging to console through `Console.WriteLine`, instead of that `Info` extension method

How are you running your spec? I'm going through our VS adapter. Here are the results:

![dummy-test-results](https://cloud.githubusercontent.com/assets/3185573/17265687/6390cc7e-55f1-11e6-93f7-71ea7aa68bb1.png)

Anyway will have a look at test cases and the aforementioned line code.

**Comment by raghur** [comment]
I'm running the test from the command line runner.  Pasted your class in and ran it with similar results
Have you tried running with the NspecRunner?

```
D:\code\iotnext\IotNext.ApiClient\src>packages\nspec.1.0.7\tools\NSpecRunner.exe IotNext.ApiTests\bin\Debug\IotNext.ApiTests.dll --tag dummy2

Dummy2 Specs
  describe scenario
    should run (31ms)
    takes longer (1s)
    a pending spec - PENDING

**** FAILURES ****

nspec. Dummy2 Specs. describe scenario. a pending spec.
'xit' cannot be set to an async delegate, please use 'xitAsync' instead
```

**Comment by BrainCrumbz** [comment]
Thanks for feedback. The error is actually visible also in VS test runner when debugging, but otherwise it gets swalloved somehow. Currently looking at it.

**Comment by BrainCrumbz** [comment]
Please have a look at commits until [this one](db46a725524c2038f820ca11d7f354adb9aac271), they should fix this.

**Comment by amirrajan** [comment]
I'll merge and deploy as soon as I get a thumbs up. The commit looks good.

**Comment by raghur** [comment]
@braincrumbz the link is broken

**Comment by raghur** [comment]
Never mind... Found the commit... Do you want me to pull this commit and build and test? Don't know enough of the code though to content on it

**Comment by BrainCrumbz** [comment]
Sorry about that, somehow the link had only the commit ID, not the whole URL. Now's fixed.

If you could, it'd be enough to try testing with NSpec dll built out of that commit, in place of the one you already have within NSpec package folder in your project. I think this is the kind of thumbs up @amirrajan was expecting.

**Comment by raghur** [comment]
Ok - I built it with that commit (actually latest master - and still see the issue)

```
**** FAILURES ****

nspec. Dummy Specs. describe scenario. a pending spec.
'xit' cannot be set to an async delegate, please use 'xitAsync' instead
```

**Comment by BrainCrumbz** [comment]
Uhm. Trying from console with aforementioned `Dummy_Specs` class:

```
Dummy Specs
  describe scenario
    should run (357ms)
    takes longer (1s)
    a pending spec - PENDING

3 Examples, 0 Failed, 1 Pending
```

**Comment by raghur** [comment]
Ah - my fault - so I compiled against Nspec.dll from the commit you listed but used old nspecrunner

..Duh..

**Comment by BrainCrumbz** [comment]
Well, yeah, the change actually is in NSpec, not NSpecRunner, but then if the old NSpecRunner was still using the *original* NSpec.dll, I guess you were missing the change.

**Comment by raghur** [comment]
Closing the ticket
