### ISSUE TITLE
NSpec website is broken again: (╯°□°)╯︵ ┻━┻

### ISSUE THREAD

**Issue by amirrajan** [mattflo/NSpec#134]

**Comment by BrainCrumbz** [comment]
Not sure it could fit the bill, but by chance one of our team just came through this project: https://github.com/louthy/best-form, basically a C# parser that generates reference docs:

> The best form of documentation is the code itself
> This is a C# doc-gen tool
> Parses C# source code to extract the XML documentation as well as a fully tokenised structure of the code itself
> Uses the LanguageExt.Parsec library to parse the raw C# source
> Provides a virtual DOM that is actually a reader monad to project the tokenised structure into HTML markup
> Generates doc-pages that look very much like the .NET Core docs
> See the language-ext API reference for a demo of this tool

It is used by [language-ext](https://github.com/louthy/language-ext) functional C# library, from he same author.

**Comment by amirrajan** [comment]
reverted to a previous version of the website. band aid for now.
