### ISSUE TITLE
Cleanup obsolete projects, build scripts and files

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#138]
After some chatting and thanks to @amirrajan review, here's a list of obsolete items that should be removed from repository: 

- [x] NSpec.GallioAdapter project
  * in [dedicated](https://github.com/mattflo/NSpec/tree/chore/cleanup-obsolete-projects) branch
- [x] NSpec.crunchsolution.local.xml files in several projects
  * in #137 
- [x] .nuget folder
  * in #137 
- [x] VS 2012 solution
  * in #137 
- [x] TDNetRunner folder
  * in dedicated branch
- [x] .userprefs
  * in #137 
- [x] watcher_dot_nets.rb, dotnet.watchr.rb scripts
  * in dedicated branch
- [x] nspec.watchr script
  * in dedicated branch
- [x] red/green.png files
  * in dedicated branch
- [x] .DotSettings (TBC)
  * in dedicated branch

Further related changes:

- [x] Adapt CONTRIBUTING.md where it mentions *dotnet.watchr.rb*

This is to ease porting to .NET Core, so ideally should be done before that or at same time.

**Comment by BrainCrumbz** [comment]
@amirrajan items left to check/edit/delete are solution NSpec.sln.DotSettings file and CONTRIBUTING.md. What to do with those? Tnx

**Comment by amirrajan** [comment]
I'll take a look.

**Comment by amirrajan** [comment]
I updated CONTRIBUTING.md. I'm fine deleting the `.dotsettings` file.
