### ISSUE TITLE
describe_Conventions specs are basically empty

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#144]
Current version of [describe_Conventions.cs](https://github.com/mattflo/NSpec/blob/f74d2df68c79557fef9fb9148c96cd0f52d48035/NSpecSpecs/describe_Conventions.cs) in NSpecSpecs project is basically empty.

What should be the original intent of testing that? Or should those just be dropped?

**Comment by amirrajan** [comment]
At one point NSpec was going to allow test discovery for tests that were title cased (in addition to  underscores). It was never really implemented and frankly I'm not fond of it anyways. So we can kill that plus the class entirely.
