### ISSUE TITLE
Question: Is there a way to get code coverage tools to recognize NSpecs specs?

### ISSUE THREAD

**Issue by danielterabyte** [mattflo/NSpec#146]
Hi guys, first of all I don't know if here is the rigth place to ask this question. So, if I did something wrong please let me know and I really sorry.

Well, we have an application using MSTest for unit and integration tests and when we run the native tool for code coverage in Visual Studio it shows the coverage of those tests.

We want to start to use NSpec because of the BDD way but, sadly, NSpec tests are not recognized by code coverage visual studio tool and being able to be scored in code coverage is the only thing blocking the use of the NSpec.

Is there some way to do it? 

I saw in another issue from 2012 that is possible to use NSpec with any code coverage tool we want it (here we could use dotCover too). But I failed to understand how to do it (there are broken links and is something old, so I don't know if it still valid).

So, if it is possible to have metrics about code coverage from specs written with NSpec can you show me (as if I was an extremely noob) how to achieve that?

Thank you all for the great tool NSpec is.

p.s.: Sorry for my english (or lack of it). I am not a native speaker.

**Comment by amirrajan** [comment]
Essentially you can put `DebuggerShim.cs` as a file in your test project: https://github.com/mattflo/NSpec/blob/v1.0.7/NSpecSpecs/DebuggerShim.cs

You can then run that single test in the `DebuggerShim` to get coverage.

**Comment by amirrajan** [comment]
Here is another example: https://gist.github.com/Ang3lFir3/981023

**Comment by danielterabyte** [comment]
Sorry for the delay.

I will try and post back here the result.

Thank you @amirrajan

**Comment by danielterabyte** [comment]
Greetings!

Well, now I am able to see results from nspec in code coverage of VS. But something is wrong.

When I choose "Test -> Analyze Code Coverage -> Whatever" it shows the coverage but only of test assembly. But it should list the production code too (right?!).

Another weird thing is that I made a failing test, but when a ran the coverage, the debuggershim appears green. 

All I did was uncomment in debuggershim those test attributes, changed the should_be to fluentAssertions (because should_be was erroring to find some NUnit dependecy file).

I tried with MSTest and NUnit attributes in debuggershim. There was no difference in results.

I always think first that every problem is me doing something wrong. But I am not seeing where in this case. 

The comments in debuggershim states that I can use it with TestDriven.net and Resharper. Is those 2 the only ones (because I am using the built in code coverage tool in VS)?

Let me know if I wrote something wrong that you were not able to understand.

Thanks.

**Comment by amirrajan** [comment]
>The comments in debuggershim states that I can use it with TestDriven.net and Resharper. Is those 2 the only ones (because I am using the built in code coverage tool in VS)?

I'm pretty sure it works with TDD.net (at least that's what I remembered using when I was needing to run coverage metrics).

>Another weird thing is that I made a failing test, but when a ran the coverage, the debuggershim appears green.

You can put something like this as the last line inside of the shim test method.

```
if (runner.Failures().Count() != 0)
                Assert.Fail("Some NSpec test failed");
```

**Comment by danielterabyte** [comment]
`if (runner.Failures().Count() != 0) Assert.Fail("Some NSpec test failed");`

It does not worked. 

And the coverage is showing just the specs code. Nothing about the production code is listed. 

My debuggerShim is this:

`
[TestFixture]
public class DebuggerShim
{
    [Test]
    public void debug()
    {
        var tagOrClassName = "class_or_tag_you_want_to_debug";

        var types = GetType().Assembly.GetTypes(); 
        // OR
        // var types = new Type[]{typeof(Some_Type_Containg_some_Specs)};

        var finder = new SpecFinder(types, "");

        var tagsFilter = new Tags().Parse(tagOrClassName);

        var builder = new ContextBuilder(finder, tagsFilter, new DefaultConventions());

        var runner = new ContextRunner(tagsFilter, new ConsoleFormatter(), false);

        var results = runner.Run(builder.Contexts().Build());

        //assert that there aren't any failures
        results.Failures().Count().Should().Be(0);
    }
}`

Nothing fancy, I just changed the assertion to be used with fluentAssertions.
I have just two projects: Production and Specs. I don't know why the production code is not being present in results. I don't even know if it is something related to NSpec or another thing...

I really appreciated the help. Thanks.

**Comment by BrainCrumbz** [comment]
Not really helpful here, sorry. Totally unrelated, and not changing anything w.r.t. current issue, with FluentAssertions you could also go with `results.Failures().ShouldBeEmpty()` so to better convey meaning.

**Comment by amirrajan** [comment]
You may also want to take a look at this: https://github.com/provegard/NSpecInNUnit

Maybe @provegard may have some input on code coverage implementations.

**Comment by provegard** [comment]
I just updated that repo a bit with a newer version of the shim/base class. I added a class `cover` that you can run with dotCover to see test coverage.

**Comment by danielterabyte** [comment]
We are running others issues (I am going to vacation time hehe) and nspec now is suspended. But I will try and come back to let you know if worked. Really appreciated the attention. Thanks.

**Comment by BrainCrumbz** [comment]
Closing this for now, as current issue seems overcome. Feel free to reopen, or create new issues for new needs.

**Comment by danielfoxp2** [comment]
Greetings, my vacation is over.

@provegard I looked to your repo of Nspec in NUnit and you states that it only works with NUnit 2. Is it still being true? Here I am using NUnit 3.

thanks.

**Comment by provegard** [comment]
@danielfoxp2 IIRC that's because NSpec has a reference to NUnit 2. Or because NUnit 3 changes how test data providers can be created. I don't remember the details, but I can check again. Could you open an issue in my repo?

**Comment by BrainCrumbz** [comment]
There should be no more dependency on NUnit as of 2.0.*

**Comment by BrainCrumbz** [comment]
Yep, those are empty:

https://github.com/nspec/NSpec/blob/master/sln/src/NSpec/project.json#L12

https://github.com/nspec/NSpec/blob/master/sln/src/NSpec/project.json#L17
