### ISSUE TITLE
Restore repository after forced push

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#147]
@amirrajan a screenshot of top level directory at commit [Merge pull request #143 from mattflo/chore/dotnet-core-1.0](https://github.com/mattflo/NSpec/commit/6040cce68a68d1a5c8f1f17c6d35cc32c6e984f8) from Nov 18th:

![nspec-dir](https://cloud.githubusercontent.com/assets/3185573/21308621/0bde3854-c5db-11e6-8e9b-b8e12112273f.png)

Now, the same screenshot taken at most recent commit [I done screwed up](https://github.com/mattflo/NSpec/commit/df4f22eb62ac3730997e450d1efdab9dc9b0e636) from Dec 13th:

![nspec-recent_2](https://cloud.githubusercontent.com/assets/3185573/21308736/8e082ed4-c5db-11e6-809c-f3627f173c95.png)

It looks like there's definitely something different. Not sure all those directories should be there in the first place. Are those remainings from the website branch? If so, how to fix that? 

Tnx

**Comment by amirrajan** [comment]
I'd say just force push what you have in your local history before I caused master to diverge

**Comment by BrainCrumbz** [comment]
Ok. Just did it. Feel free to close this once you fetch and everything seems ok on your side as well.
