### ISSUE TITLE
NSpecRunner unable to pull in config file

### ISSUE THREAD

**Issue by DrSammyD** [mattflo/NSpec#41]
I am loading a configuration file inside of my tests. When I run the tests using the debugger shim, the test passes and is able to successfully load the config file. However, when I run the tests using NSpecRunner, attempting to load that file throws an error. I've run the test using NUnit and ReSharper, both are able to run the debugger shim and successfully pull in the config file. The file is an nhibernate.config file.

**Comment by amirrajan** [comment]
Still relevant. Should be resolved when devs are required to build their own console app/program.cs (which will be stupid simple I promise).

**Comment by amirrajan** [comment]
Gonna close this because you can build your own console app pretty easily. That plus .Net core removes all of the AppDomain mess. Here is a sample of a console app you can build:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NSpec;
using System.IO;
using NSpec.Api;

static void Main(string[] args)
{
    var types = GetType().GetTypeInfo().Assembly.GetTypes();
    var finder = new SpecFinder(types, "");
    var tagsFilter = new Tags().Parse("");
    var builder = new ContextBuilder(finder, tagsFilter, new DefaultConventions());
    var runner = new ContextRunner(tagsFilter, new ConsoleFormatter(), false);
    var results = runner.Run(builder.Contexts().Build());

    if(results.Failures().Count() > 0)
    {
        Environment.Exit(1);
    }
}
```
