### ISSUE TITLE
Sub context before_all running before parent before_each

### ISSUE THREAD

**Issue by DrSammyD** [mattflo/NSpec#51]
Is there a way to have a before_all inside of a context only run after the parent context's before_each?

for example I'm doing the following gist

https://gist.github.com/4268265
<script src="https://gist.github.com/4268265.js"></script>

new_session_start inherits from nspec_driver

notice that driver is not created until the before each is run, so if before_all runs before that, the driver will not exist.

I also created another test class seeing if the behavior was different if it was all part of the same class, but it is not.

I tried doing a base.beforeEach.Invoke(), but I can't actually call that. Any ideas? Is this intended functionality? 

Edit: I've edited my gist to only test if before_all runs before a parent before_each.

**Comment by amirrajan** [comment]
See wiki (probably should be added to website). /cc @BrainCrumbz
