### ISSUE TITLE
AppDomain and CurrentDirectory is different from NUnit.

### ISSUE THREAD

**Issue by dacat** [mattflo/NSpec#61]
Let me preface by saying I am not an expert in C# or the .NET framework. I just stumbled on this. 

When I run NUnit tests, either from ReSharper or with in VS2012, the AppDomain.CurrentDomain.BaseDirectory is the build output path from the project properties. ex 

**c:\vsprojects\mySolution\target\bin\debug\x64**

Also the Directory.CurrentDirectory during launch is also the the build output path from the project properties, same example as above.

However when your run NSpecRunner from the package management console, obviously, the CurrentDirectory is current path where you executed NSpecRunner from and the AppDomain.CurrentDomain.BaseDirectory is 
**c:\Users\myuser\documents\Visual Studio 2012\Projects\mySolution\packages\nspec.0.9.67\tools.**

Honestly I don't know if its relevant to even report it. Its just a minor inconsistency between the two, and I only stumbled upon it consuming someone else's library that relies on have a AppDomain.CurrentDomain.BaseDirectory\Bin directory.

Thank you for developing NSpec :)

**Comment by amirrajan** [comment]
Still relevant, but should be resolved when NSpec requires all devs to create their own Program.cs (which will be stupid simple)

**Comment by BrainCrumbz** [comment]
This should be closed once dotNET Core port is fully ready, as there's no AppDomain in ported version (at least as of now, future Core versions might add some parts of BCL back).

**Comment by amirrajan** [comment]
This brings me tears of joy.

**Comment by BrainCrumbz** [comment]
Closing as library has been ported to .NET Core, and in current implementation there's no use of AppDomain
