### ISSUE TITLE
NSpec doesn't handle strong-name signed unit test DLL

### ISSUE THREAD

**Issue by JVimes** [mattflo/NSpec#72]
I have to strong-name sign my unit test DLL to friend it to a product DLL. After signing, there's an error, "Referenced assembly 'NSpec' does not have a strong name". I can disassemble and then sign/reassemble the NSpec DLL, but that's a hassle and other frameworks (xBehave.net/xUnit) work OOTB in the same situation. Perhaps NSpec can do what they're doing. I've seen them work with both signed and unsigned unit test DLLs.

**Comment by amirrajan** [comment]
Will not fix. Recommendation is to compile from source and strong name yourself.
