### ISSUE TITLE
IL merged nunit doesn't play nice with other versions of explicitly referenced nunits

### ISSUE THREAD

**Issue by ot-matt-florence** [mattflo/NSpec#73]
This is a regression introduced somewhere between v66 and v68. It works fine on v66 but breaks on v68. If you have nspec and another version of nunit referenced in the same project. And you are using nspec assertions. Then running the nunit tests results in this error:

<pre>System.IO.FileLoadException : Could not load file or assembly 'nunit.framework, Version=2.5.7.10213, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77' or one of its dependencies. The located assembly's manifest definition does not match
the assembly reference. (Exception from HRESULT: 0x80131040)
at NSpec.AssertionExtensions.Is(Object actual, Object expected)</pre>

also for reference the version of nunit that is referenced by the test project is 2.6.3

**Comment by amirrajan** [comment]
Dependency on NUnit has been removed.
