### ISSUE TITLE
Team City

### ISSUE THREAD

**Issue by cesarmm** [mattflo/NSpec#74]
I have TeamCity as CI framework and I want run the tests over it, is it possible?

Thanks.

**Comment by CRuppert** [comment]
Actually, I am having trouble with this too. The XUnitFormatter seems to create a root node called test-results, which xUnit does not seem to have in any documentation that I can find. Can you tell me which version of xUnit that would match the schema for?

In addition, the formatter also nests cases inside of <results> nodes, which I cannot seem to find in any xUnit documentation or samples.

**Comment by amirrajan** [comment]
Thanks for the link.
