### ISSUE TITLE
nspec.org seems to be broken

### ISSUE THREAD

**Issue by brannon** [mattflo/NSpec#77]
http://nspec.org

Returns a GitHub Pages error:

Site Disabled

Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.

Are you the site owner? You can quickly fix this issue by updating the DNS record for your Pages site:

If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a CNAME record that points to your-username.github.io.
If you're not using a subdomain (example.com), make sure you have two A records set to the following IPs: 192.30.252.153 and 192.30.252.154
More detailed instructions for setting up a custom domain with GitHub pages are also available if you need more guidance.

You can find more information about these changes in our GitHub Pages legacy IP deprecation blog post. If you have any questions, please contact support.

**Comment by mattflo** [comment]
Should be up as soon as dns propogates. Thanks for the heads up.

On Tue, Feb 3, 2015 at 10:56 AM, brannon <notifications@github.com> wrote:

> http://nspec.org
>
> Returns a GitHub Pages error:
>
> Site Disabled
>
> Oh no! It looks like this Pages site has been disabled due to a
> misconfigured custom domain.
>
> Are you the site owner? You can quickly fix this issue by updating the DNS
> record for your Pages site:
>
> If you're using a subdomain (coolthing.example.com, www.example.com,
> etc.), make sure you have a CNAME record that points to
> your-username.github.io.
> If you're not using a subdomain (example.com), make sure you have two A
> records set to the following IPs: 192.30.252.153 and 192.30.252.154
> More detailed instructions for setting up a custom domain with GitHub
> pages are also available if you need more guidance.
>
> You can find more information about these changes in our GitHub Pages
> legacy IP deprecation blog post. If you have any questions, please contact
> support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattflo/NSpec/issues/77>.
>



-- 
- Matt Florence
http://mattflo.com

**Comment by amirrajan** [comment]
fixed
