### ISSUE TITLE
Installed SpecWatchr but no ruby files

### ISSUE THREAD

**Issue by dr43058** [mattflo/NSpec#78]
Hi, 
I have installed Specwatchr via nuget package manager console(install-package specwatchr), but there are no ruby files in my solution tree. I am particularly looking for dotnet.watchr.rb but it is not getting installed. Although it does install a file called specwatchr-usage.txt
VS 2012 PRO - VER 11.0 
.NET FW 4.5
NSPEC VER 0.9.68
SPECWATCHR VER 1.7.5

**Comment by dr43058** [comment]
Never mind, I wasn't looking at the root solution directory, but instead, I was looking at the project directory, my bad. All the files are there. Closing the issue!

**Comment by amirrajan** [comment]
That's good to hear. Sorry for getting to this so late. Did you have any issues installing the `watchr` gem?
