### ISSUE TITLE
How to do should_behave_like?

### ISSUE THREAD

**Issue by petemounce** [mattflo/NSpec#80]
Is there an illustration somewhere for how I can get rspec-like `should_behave_like`?

**Comment by amirrajan** [comment]
Abstract classes are the closest thing to behaves like. Basically you can create an abstract class with contexts and any class that inherits from it will have all specifications execute at _their_ level.

**Comment by amirrajan** [comment]
Here are a few sample tests that may help:

https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_RunningSpecs/describe_abstract_class_examples.cs

https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicModel/describe_Validation/acceptance.cs

**Comment by amirrajan** [comment]
Probably good to have a sample in the website /cc @BrainCrumbz

**Comment by BrainCrumbz** [comment]
Agree with your proposal. If you mean on github pages (as opposed to the website-under-remake), we could do that.
