### ISSUE TITLE
Is this project still actively developed and supported?

### ISSUE THREAD

**Issue by joelpresence** [mattflo/NSpec#82]
Hi,

It looks like there hasn't been a release or commit for some time.  Is this project still undergoing active development and support?  I just wanted to check before I commit to using it.  :-)

Thanks!

**Comment by amirrajan** [comment]
Yep. It's stable as far as I know. I've got pretty large test suites against it and they work like a charm.

**Comment by joelpresence** [comment]
Thanks!

On Jun 26, 2015, at 5:17 PM, Amir Rajan <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep. It's stable as far as I know. I've got pretty large test suites against it and they work like a charm.

**Comment by amirrajan** [comment]
You're welcome! One thing I would recommend is that instead of creating a class library and running it through NSpec.exe. I'd just create a console app and copy and paste this code into `static void main`: 

```
    {
        var tagOrClassName = "class_or_tag_you_want_to_debug";

        var types = GetType().Assembly.GetTypes(); 
        // OR
        // var types = new Type[]{typeof(Some_Type_Containg_some_Specs)};
        var finder = new SpecFinder(types, "");
        var builder = new ContextBuilder(finder, new Tags().Parse(tagOrClassName), new DefaultConventions());
        var runner = new ContextRunner(builder, new ConsoleFormatter(), false);
        var results = runner.Run(builder.Contexts().Build());

        //assert that there aren't any failures
        results.Failures().Count()
```

**Comment by BrainCrumbz** [comment]
Why do you recommend this approach, instead of e.g. taking advantage of NSpec Adapter for VS TestRunner found in VS Extension Gallery?

**Comment by joelpresence** [comment]
I’m running on a Mac using MonoDevelop.  Will this approach still work - obviously I can’t run the exe?

Thanks.

On Jun 27, 2015, at 8:37 AM, Amir Rajan <notifications@github.com<mailto:notifications@github.com>> wrote:


You're welcome! One thing I would recommend is that instead of creating a class library and running it through NSpec.exe. I'd just create a console app and copy and paste this code into static void main:

    {
        var tagOrClassName = "class_or_tag_you_want_to_debug";

        var types = GetType().Assembly.GetTypes();
        // OR
        // var types = new Type[]{typeof(Some_Type_Containg_some_Specs)};
        var finder = new SpecFinder(types, "");
        var builder = new ContextBuilder(finder, new Tags().Parse(tagOrClassName), new DefaultConventions());
        var runner = new ContextRunner(builder, new ConsoleFormatter(), false);
        var results = runner.Run(builder.Contexts().Build());

        //assert that there aren't any failures
        results.Failures().Count()

**Comment by amirrajan** [comment]
Here is a sample of NSpec on Mono: https://github.com/amirrajan/NSpec-Mono-Binaries

**Comment by amirrajan** [comment]
Sorry for the late reply, I was out of town.
