### ISSUE TITLE
Async before, async expectation

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#83]
Does the NSpec framework support `async` functions set on `before`? And on `it[]` expectations? E.g. (just a dummy example to get what we're referring to):

```c#
// [...]
void Give_some_condition()
{
  before = () => setCondition();

  context["When something async happens"] = () =>
  {
    before = async () => { await doSomethingAsync(); };
  };

  it["Should verify after async operation completed"] = async () => 
  {
    await Task.Delay(someTimeInMillis);

    verifyItCompleted();
  };
}
```

At first I thought the framework did support, but then some async expectations we're completing successfully even if that was not supposed to be, so now I think the test just passes on and completes expectation successfully without really coming back to the *moveNext*, where the actual condition is tested.

**Comment by amirrajan** [comment]
@mattflo just pulling Matt into this. Can you provide some background on the benefit of this? Is it because you're trying to specifically test async api's for you classes?

Here is how contexts are executed: https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/Context.cs#L89

**Comment by amirrajan** [comment]
And this: https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/Context.cs#L133

**Comment by BrainCrumbz** [comment]
No, in that particular case I needed to wait for some time, and it came natural to do that with async. In order to make that work, in the end I switched to sync execution, dropping `await` in favour of `.Wait()`. 

But then I was wondering what happens if an async lambda is provided, maybe one should be warned that it is not supported and will not *really* work (of course, if that's the actual case).

Will have a look at the source you referenced.

**Comment by amirrajan** [comment]
Could you give me a distilled example? I'd be happy to try to implement it if it's something that will help you out :-)

**Comment by BrainCrumbz** [comment]
Trying to make up an example here, it should make sense. Please correct me if I'm wrong:

```c#
public interface IDataLayerProvider
{
  Task<RawDataResource> LoadRawResource(string resourceUrl);
}

public BusinessLayerRepo
{
  public BusinessLayerRepo(IDataLayerProvider provider)
  {
    _provider = provider;
    //...
  }
  public async Task<BusinessEntity> GetResource()
  {
    // ...
    RawDataResource rawResource = await _provider.LoadRawResource(_resourceUrl);
    // ...
    return someBusinessEntity;
  }
}

// inside unit tests class:

// ...
BusinessLayerRepo businessRepo;  // class under test
BusinessEntity actualBusinessEntity;
RawDataResource providedDataResource;
BusinessEntity expectedBusinessEntity;

void Given_raw_resource_is_available()
{
  before = () => 
  {
    // setup the mockProvider to return providedDataResource when LoadRawResource is invoked
  };
  
  context["When asking for business entity"] = () =>
  {
    before = async () => 
    {
      actualBusinessEntity = await businessRepo.GetResource();
    };

    // using FluentAssertions here
    it["Should convert biz entity"] = () => actualBusinessEntity.Should().Be(expectedBusinessEntity);
  };
}
```

**Comment by BrainCrumbz** [comment]
Of course, along the same lines, one can have an `it[""]` expectation set on an async lambda. It's enough to have something like:

```c#
it["Should complete some async operation"] = async () =>
{
  OperationResult actual = await instanceUnderTest.DoOperationAsync();

  actual.Should().Be(expected);
}
```

**Comment by amirrajan** [comment]
Let me see what I can make work.

**Comment by BrainCrumbz** [comment]
By my (unexisting) knowledge of how NSpec works, I really don't know if it's correct that it should detect whether an async method has been passed to `before` or `it[]`. If that should be needed, here's the [hint I found on SO](http://stackoverflow.com/questions/19024014/check-if-action-is-async-lambda) (although it is strongly not recommended by Jon Skeet himself)

**Comment by amirrajan** [comment]
I could create an api called `asyncBefore` and `asyncIt`. What do you think?

**Comment by BrainCrumbz** [comment]
In principle I think that would do, but it may look "less friendly" and a bit more involved than the scenario where the framework just detects if the lambda (or method) needs to be awaited or not. One has to remember to assign either here or there for `it`, and here or there for `before`. And remember to change that if things change (and they will). 

Please allow me to better explain: NSpec has this opportunity because anyway one has to explicitly assign work to-do to those special members (`it` and `before`), so NSpec can take advantage of that and build a convention on top of that: *if it's async, set it to asyncXxx*. But other frameworks do not have this opportunity right away, and still they make async work, without using a conventional name or prefix or stuff like that. I'd say: if other frameworks successfully rely on some other mechanism (or convention, if you want) to detect awaitable functions, without asking the user to explicitly remember to do something, why can't NSpec do the same?

E.g. as done [here](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/AsyncInvocationRegion.cs#L81-L85)

Please consider that I don't know about NSpec internals, so maybe it's just not the way it works, (maybe it does not access `MethodInfo`, just as an example).

Maybe you want to gather more "consensus" over this choice, before putting that into concrete.

**Comment by amirrajan** [comment]
I think you're right. I like the idea of _not_ forcing the developer to decide and the framework just handling it by detecting whether it's an async block or not. Would you like to take a stab at doing this? I'd be happy to get on G+ and make sure you have to solution up and running locally and maybe talk through some of the touch points?

**Comment by BrainCrumbz** [comment]
I guess the async detection can basically be copied over from some other implementation. I wonder about the touch points in the framework, e.g. where `before` and `it` are *enumerated* (so to say) and where they are executed. Can you share some hints just to have a brief look, before moving forward? Tnx

**Comment by amirrajan** [comment]
I'll give you (and others) as much information here as possible. Tomorrow promise :-)

**Comment by amirrajan** [comment]
First thing to get familiar with is how tests are found and built up. High level, NSpec first builds up tests, then executes them. Here is a distilled version of how that happens:

```
        var types = GetType().Assembly.GetTypes(); 
        // OR
        // var types = new Type[]{typeof(Some_Type_Containg_some_Specs)};
        var finder = new SpecFinder(types, "");
        var builder = new ContextBuilder(finder, new Tags().Parse(tagOrClassName), new DefaultConventions());
        var runner = new ContextRunner(builder, new ConsoleFormatter(), false);
        var results = runner.Run(builder.Contexts().Build());

        //assert that there aren't any failures
        results.Failures().Count().should_be(0);
```

**Comment by BrainCrumbz** [comment]
Thanks for the info and summary on how NSpec works, that clarifies really quick many things, and thanks for suggestions on how to go for the async case. 

I did not get exactly what is a `MethodExample` and what instead is an `Example`. Thinking about a sample test suite, what/where are they? Maybe one is the void method in the test class, and the other is a sub-test created with a context within the void method?

About running tests: I can open the root `NSpec.sln` solution in VS2013 Community Ed. with NUnit (and NSpec) Adapter installed, and I can rebuild successfully the solution,  
When I open the Test Explorer and that starts enumerating all tests, I got some error from the NSpec test adapter itself, but I guess those are related to the many sample NSpec test cases disseminated here and there.  
Instead the NUnit adapter runs fine, finds a number of test cases. When I run that, it gives 2 skipped tests and 5 failed. Should we check this out of this issue thread?

![image](https://cloud.githubusercontent.com/assets/3185573/8742537/ab9e1338-2c66-11e5-8e93-477b90513ca4.png)

**Comment by amirrajan** [comment]
>I did not get exactly what is a MethodExample and what instead is an Example.

This is a `MethodExample`:

    class describe_something : nspec
    {
        void it_should_work() { } //MethodExample
        void given_something()
        {
            it["should also work"] = () => { } //Example
        }
    }

> Thinking about a sample test suite, what/where are they? Maybe one is the void method in the test class, and the other is a sub-test created with a context within the void method?

I'd say the sample suites here are the best ones (I'd put your async sample there to): https://github.com/mattflo/NSpec/tree/master/NSpecSpecs/describe_RunningSpecs

The two skipped should be fine. 

As for the failed tests, they failing probably because the process working directory is different between our computers. The `ouput_tests` are trying to find `NSpecRunner.exe`, but can't find it (you can ignore these for now if you'd like): https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_output.cs#L59

**Comment by amirrajan** [comment]
Also, FWIW. I'm with you every step of the way on this. It'd be great if you can get this working and hopefully contribute to a popular testing framework. At some point I'll make sure this works well on the new x-plat stuff Msft is putting out :-)

**Comment by BrainCrumbz** [comment]
For one thing: NSpecSpecs project runs against .NET 4.0, while async/await *usually* needs .NET 4.5.

I can get the project to compile (and to *understand* async/await) installing the official package `Microsoft.Bcl.Async`. But then NSpecSpecsVB project of course starts complaining. 

Before we move further, which approach should we go? Promote both projects to .NET 4.5, or try to go on on both with .NET 4.0 + Bcl.Async package?

**Comment by BrainCrumbz** [comment]
Besides the target version topic from above, there's another (major) point which deserves attention, despite all the nice thoughts about letting the framework figure out everything by itself, without much user manual intervention.

Very likely, a user would set an async `before` by writing 

```c-sharp
before = async () => await DoSomethingAsync();
```

Any lambda expression (async or not) has no type defined by its own: the type of the expression it represents gets defined by compiler depending on the target, i.e. on what's on the left side of assignment.

So if `nspec` keeps on having a `Action before` property, the user still can assign the async lambda to it, but that will get converted to an `Action` *wrapper* (so to say), and its return type will get completely lost (it will turn to `void` actually). Sticking the example above, the code would actually turn into something similar to:

```c-sharp
before = () => AsyncVoidFunc();

async void AsyncVoidFunc()
{
  await DoSomethingAsync();
}
```

At that point, framework lost any reference to the task to be awaited. The only way to get a hold of it, so it can be awaited, is to pass the lambda to a properly typed identifier on the left side. In our scenario that would mean for `nspec` class to have a `Func<Task> before`. But then again, that would break the regular sync. assignment: `before = () => DoSomething();`.

If all this is correct, it seems to prevent having a unique `before` to pass both sync and async arrange method.

**Comment by amirrajan** [comment]
I think starting off having an `asyncBefore`, `asyncIt`, etc method may be better.  There's nothing stopping a dev from inheriting `nspec` and creating their own consolidation method. [Example](https://github.com/amirrajan/Oak/blob/master/Sample%20Apps/BorrowedGames/BorrowedGames.Tests/_borrowed_games.cs#L17).

As for targeting a version. I'd say let's bite the bullet and just upgraded to 4.5 (I'll do a 1.0 release to let others know that this is a breaking change). I'd say it's fairly low risk to upgrade your test project to 4.5.

**Comment by BrainCrumbz** [comment]
Thanks for replies.  

Regarding `asyncBefore` etc., ok, let's go with that (on a side note: I did not get what you mean with *create their consolidation method*, anyway...)

Regarding .NET version to target, we'll upgrade main `NSpec` & `NSpecSpecs` projects to .NET 4.5, and possibly more projects if needed. Thus we can drop the `NSpec-4.5` & `NSpecSpecs-4.5` parallel projects, and we can also drop all those `#if NET_4_5` (actually, it was `#if ASYNC`).

Next thing to decide:  
we went on introducing an `nspec.asyncBefore` property down the chain, then climbed up all the way, introducing a bunch of `async Task RunAsync()` wherever there was a `void Run()`, and the same for other methods that *run things*. As you'll be aware, the async/await couple is like a virus: once you introduce them somewhere, they spread everywhere.  
Now to the point: if you go async *all the way* (as suggested by experts, e.g. Stephen Cleary) you arrive to all the components being part of NSpec framework, and up to the NUnit tests that test the framework.

If you want to *break* the chain at some point, switching to blocking synchronous code, you should make sure that all the `await` are followed by `.ConfigureAwait(false)`, otherwise the code might deadlock. For one thing, the NSpec framework cannot control what happens to the `await` used in code under test, nor in the test code itself. As a matter of fact, we tried breaking the chain and at some point, in some `Run` method, we started waiting synchronously. Result: deadlock right away in the code testing `asyncBefore`.

On the other hand, I favour the idea of leaving the async/await as much as possible close to client code, and not spreading in framework. Ideally, why should the test framework really allow for async execution in its internals? It has nothing more *important* to do than running tests, and it doesn't make a lot of sense to start doing other things in the meantime.  
Having a look at NUnit, it looks like that they actually just `.Wait()` on the very first occasion they met an async method from client code, and there's no trace of async/await in framework internals. But of course NUnit does not lock.  
... so it must be our implementation :)

**Comment by amirrajan** [comment]
>Regarding .NET version to target, we'll upgrade main NSpec & NSpecSpecs projects to .NET 4.5, and possibly more projects if needed. Thus we can drop the NSpec-4.5 & NSpecSpecs-4.5 parallel projects, and we can also drop all those #if NET_4_5 (actually, it was #if ASYNC).

I'd say not worry about that at all. Most of the people that use NSpec are fairly progressive and a test suite upgrade to 4.5 shouldn't cause friction if we SemVer.  So I wouldn't worry about the `if defs` and just jump to VS 2015 Community Edition and 4.5.

>As you'll be aware, the async/await couple is like a virus: once you introduce them somewhere, they spread everywhere.

Tell me about it >_<. I'd say use your discretion. We can go as far as having an `nspec_async` class that just has async versions of `it` `before`, etc.  So you either full opt in or don't (just an idea).

>and up to the NUnit tests that test the framework. 

Oye...

>But of course NUnit does not lock.

Wouldn't it be helpful if the libs are tested in an Async fashion to give the dev confidence that their code works? Just throwing that out there. I'm totally fine with taking the `.Wait()` approach too.

**Comment by jspringer2020** [comment]
Thanks for picking this up @BrainCrumbz. The way `expect<T>` works with expected exceptions also falls down without the async / await logic because exceptions are wrapped into an `AggregateException`, so the only real way to use expect with nspec and an async method is to do your own try/catch or `.Result` on the awaitable. Both are really not that friendly and have their own issues. If you decide to fork nspec and upgrade it to 4.5 let me know,,  I would like to help.

**Comment by amirrajan** [comment]
Just a note, @BrainCrumbz @jspringer2020, feel free to send me an unfinished pull request. I may be able to contribute too. That and we can have a dialog over the commits as opposed to just at the end.

**Comment by BrainCrumbz** [comment]
Hello all, a quick update (after the silence):
we already started with the parallel 4.5 projects, so the next steps will be to remove those, clean everything and upgrade existing projects to 4.5 (so yes, @jspringer2020).  
Then we think to finalize test and implementation to actually introduce the first case of async support: `asyncBefore`. The plan is to do that by going *async all the way*, i.e. from down the asyncBefore, through the framework components, up to the NUnit tests testing the framework itself.

At that point, it seems a good time to create a feature branch and publish everything on our fork (or wherever you think is better). That of course would be unfinished work, but would allow everyone to have a thought on it and figure how things could evolve, before actually doing more work.

@jspringer2020 I didn't think about that ... true, specs with exceptions will have to be revised as well. As in all this process, our first thought would be *have a look at what others did before you*, although of course some approaches might be not applicable to this framework.

**Comment by amirrajan** [comment]
Sweet! Definitely send me a pull request after the 4.5 project upgrade. I need to go in afterwards and make sure it builds on mono too.  Would it be easier if I give y'all collaborator access to the repo?

**Comment by BrainCrumbz** [comment]
Ok for the first PR after 4.5 project upgrade. So that will be on the *default* (sorry, Hg fans here) branch. About collaborator access, as long as you can review what's happening, I guess is fine.

**Comment by BrainCrumbz** [comment]
Update: we published some more *preparatory* changes on the same PR/branch, like upgrading packages and fixing some comments.

In order to simplify the 4.5 upgrade review, tests on Mono, etc. we'll leave this `async` branch as-is for now. The actual changes to introduce `asyncBefore` will be applied on a new branch starting from this one. In this way we can experiment some approach (e.g. apply async only somewhere), then switch back and create another branch to try with some other approach (e.g. async all the way).  

If you guys think there are better ways, please do suggest them, no worries.

**Comment by amirrajan** [comment]
I'll take a look first think Saturday :-)

**Comment by BrainCrumbz** [comment]
Hello all.  
Any feedback on the approach shown in `async-least`? Cheers

**Comment by amirrajan** [comment]
Getting NSpec building on OSX. See the `mono` branch. From what I've looked at so far, it looks good (having the async version returning a `Task`). I have all of this week off, so I'll get some more time to look at it during this week.

**Comment by amirrajan** [comment]
Can you elaborate more on:  `#if OFFLOAD_IN_CONTEXT`

**Comment by amirrajan** [comment]
```

**Comment by BrainCrumbz** [comment]
Re. the week off, great! :)

At this point we are still experimenting, so there are a couple of *temporary* #defines that act as switches between different ways of obtaining the same result. 
In this case, the end result is to offload the async work provided by client code to another thread, so not to deadlock in framework code. In order to get this result, framework can either:

* Offload async work directly within `SafeInvoke` extension methods, so that those methods themselves remain synchronous, and within them the client code is run on a task and waited for. In this case, `Context` is basically unaware of what's happening inside any `AsyncBefore.SafeInvoke(...);`. Such implementation can be seen when #defining `OFFLOAD_IN_SAFE_INVOKE`

* Let the `Context` be aware of and manage the async work provided by client code. So extension methods are simpler than previous scenario, and they are async (`SafeInvokeAsync`) because they just hand the async client work off to the Context. It'll be the Context's concern to create the needed task and wait for it. Such implementation can be seen when #defining `OFFLOAD_IN_CONTEXT`.

Very soon (i.e. now) one of the two approaches would be promoted, and the other will just disappear. I would judge based on concerns and responsibilities, which at the moment are not totally clear to me. If those extension methods are the only parts of framework that actually **run** client code, then I guess it can be their responsibility to take care of async client code, so `OFFLOAD_IN_SAFE_INVOKE` could be the way. While `Context` responsibility is to take care of the different hooks and their order of execution, etc. not actually having to *run* client code on its own.  
As a side note: at some point one of the commits had the two defines mixed up w.r.t. their meaning. I think that's fixed [now](https://github.com/BrainCrumbz/NSpec/commit/1168dd845b308e12574d06b0ca7e1204a5ea9a69).

Last answer (sorry for long reply): I tend to think that separating *async* test classes from *sync* test classes just because of technical reasons is not a good idea. As a user, I create test classes based on some criteria - e.g. testing a single class, or testing some funcionalities or scenarios for a single class - and very hardly this would map to async Vs sync cases. Generally a user would need to mix sync *before*s with async *before*s, as well as with sync/async *it*s and *act*s.

Unless we hit some roadblock or face some great complexity in API surface offered to user, I'd try to go with just one `nspec`.

**Comment by amirrajan** [comment]
>#defines

Cool :-)

>I tend to think that separating async test classes from sync test classes just because of technical reasons is not a good idea.

That's fine. Just thought I'd put that out there.

**Comment by BrainCrumbz** [comment]
What do you think about this asyncBefore approach, confining the async *virus* at the very border with client code? If this proves to work without deadlocks, it could be a clean way to upgrade the framework.

**Comment by amirrajan** [comment]
That's perfectly fine :-), absolute worst case the end user can subclass `nspec` and create their own dialect if they find themselves using the virus more than the default.

**Comment by BrainCrumbz** [comment]
Great :) I didn't think about this chance of user subclassing nspec class. Not sure how that could work if the framework itself is not modified as well by the user, in order to take into account the *dialect* changes, anyway...

I think I'll first move all work in progress from BrainCrumbz fork to original repo, then keep going with changes to the other hooks.

**Comment by amirrajan** [comment]
Sounds good!

Here is an example of subclassing `nspec`: https://github.com/mattflo/NSpec/issues/71

**Comment by BrainCrumbz** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

In order to implement async *examples* (i.e. `asyncIt["Should ..."]`) it looks like the actual `Example` framework class has to be split in two. A base (abstract) class with 90% of its actual funcionalities, and a derived class to implement just the **sync** part of it - that is, everything related to its `Action action` field. Then of course there'll be a derived class to implement just the **async** part of it.

Now, the question about naming (it' all related to **internal** framework entities, nothing visible to the final user). Which one do you think looks better:

```c-sharp
public abstract class ExampleBase { }
public class Example : ExampleBase { }
public class AsyncExample : ExampleBase { }
```

Vs

```c-sharp
public abstract class Example { }
public class SyncExample : Example { }
public class AsyncExample : Example { }
```

As a side note: as of now, *before* hooks are internally represented by two `Context` properties: `Before` and `AsyncBefore`. That was just to limit to the minimum the amount of changes, but it should not be taken as a constraint. We might as well rename `Before` as `SyncBefore` in the near future.

**Comment by BrainCrumbz** [comment]
My opinion:  
as long as in framework internals there's this kind of *duality* between what is sync and what is async, I would go for a clear naming separation. So e.g. `SyncExample` Vs `AsyncExample`, `SyncMethodLevelExample`Vs `AsyncMethodLevelExample`, `Context.SyncBeforeInstance` Vs `Context.AsyncBeforeInstance`. Otherwise, everytime someone's working on the framework and reads `DomainExtension.Methods()`, s/he's left wondering if that is for sync, async, both, so has to go to definition and check implementation. A sign of a not-good naming choice.

If this duality will go away with further developments, e.g. some XxxSync/ XxxAsync couples just get merged into one method, then we can switch back to a simpler naming.

**Comment by amirrajan** [comment]
I'll let @mattflo take this one. He'll get back to you.

**Comment by amirrajan** [comment]
Let's do `ExampleBase` `Example` and `AsyncExample`.

**Comment by BrainCrumbz** [comment]
That is ok. The initial approach we took on other cases is the other way around (explicit sync/async). Looking at them, do you think your proposed approach looks fine there as well?

1. [`DomainExtensions.Methods()`](https://github.com/mattflo/NSpec/blob/async-least/NSpec/Domain/Extensions/DomainExtensions.cs#L16)
1. [`Conventions.GetMethodMatchingRegex()`](https://github.com/mattflo/NSpec/blob/async-least/NSpec/Conventions.cs#L154)
1. [`Conventions.GetMethodLevelBefore()`](https://github.com/mattflo/NSpec/blob/async-least/NSpec/Conventions.cs#L96)

**Comment by amirrajan** [comment]
@mattflo and I were talking and we both felt that the "default" behavior of NSpec is Sync and shouldn't require the prefix. Conceding that parent classes and methods would need the `Base` suffix. I'd probably say that those methods should have the `Sync` removed also. 

What do you think?

**Comment by BrainCrumbz** [comment]
On the downside, explicit sync/async suffix (or prefix) wherever needed is kinda noisy, requires a lot of changes throughout code in order to be uniform. So I guess we can go with your last proposal: 

* sync-related methods & identifiers have **no sync** suffix/prefix
* async-related methods & identifiers have explicit `Async` suffix/prefix
* if the need arises for a common base class (or common helper method) that will have a `Base` suffix

**Comment by amirrajan** [comment]
:+1:

**Comment by BrainCrumbz** [comment]
Hello all. We just pushed commit [Extract common logic in AsyncMethodExample/ LevelHook](https://github.com/mattflo/NSpec/commit/bdbdcf1eed376956cca3ee818943518951b445c1). We think now the changes represent a good part of what is needed in order to make NSpec work with async. On top of my head, there are:

1. Context-level async- before, before all, act, it, xit, after, after all
1. Method-level async- before (each), before all, act (each), it, specify, after (each), after all
1. Async expect
1. Async todo

What should the next step be? Squash all commits to another branch for review?

Regards

**Comment by amirrajan** [comment]
I'm not too concerned with squashing (unless you are). If that branch is in a good point to go into master, I can run my [Oak NSpec suite](https://github.com/amirrajan/Oak/tree/master/Oak.Tests) and [Borrowed Games NSpec suite](https://github.com/amirrajan/Oak/tree/master/Sample%20Apps/BorrowedGames/BorrowedGames.Tests) against it and see if everything still works. If it does, I'd say we are good to go.

**Comment by BrainCrumbz** [comment]
Go for it! :) 

Re. squashin: I'm not too concerned about that (and we're not even that much expert with it). Maybe you guys prefer to have a single big commit when merging into master, and leave all intermediate changes within async branch.

**Comment by amirrajan** [comment]
I'll let you handle the merge back into master :-P, I'll let you know if all the Oak tests pass.

**Comment by amirrajan** [comment]
Did a smoke test against Oak's test suite and everything worked like a charm (600+ tests passed). I feel pretty good about `async-least` being merged in.

**Comment by BrainCrumbz** [comment]
Great news! Sorry for late reply, right now on holiday, so we're trying to be as far as possible from a work PC :)
I think we can go with merge as soon as we get back!

**Comment by amirrajan** [comment]
Oh man, no worries/pressure! Just wanted to make sure I'm responsive to all the hard work you're putting in.

**Comment by BrainCrumbz** [comment]
Ok, back to desk. But now it's turn for *that* work laptop to go on a break (to the repair shop). Don't remember if there were any unpublished commits on it... I guess we'll just wait until we get the laptop back. BTW, is there a way we can setup a chat?

**Comment by amirrajan** [comment]
my gchat is ar@amirrajan.net

**Comment by BrainCrumbz** [comment]
I sent you an invitation as braincrumbz@gmail.com on google hangouts (I take it that is the actual incarnation of google chat, right?)

**Comment by BrainCrumbz** [comment]
One potentially thought-provoking question: 
which one of the following variants do you think is easier to read and (with a lesser importance) also easier to type?

```c#
asyncIt["should return false"] = async () => (await GetResultAsync()).should_be(false); // #1

itAsync["should return false"] = async () => (await GetResultAsync()).should_be(false); // #2

it["should return false"] = waits(async () => (await GetResultAsync()).should_be(false)); // #3
```

**Comment by amirrajan** [comment]
I'd say 2

**Comment by amirrajan** [comment]
It's the most discoverable

**Comment by BrainCrumbz** [comment]
To me, nr. 2 looks better than 1, so at least there could be a renaming before merging. 

But in these days I found about former [Jasmine 1.3 async support](http://jasmine.github.io/1.3/introduction.html#section-Asynchronous_Support), then [Jasmine 2.0 async support](http://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support). Then about some extensions made in [atom project](https://github.com/atom/jasmine-waits-for-callback) and *especially* this `waitsForPromise` extension [here](https://atom.io/docs/v0.146.0/writing-specs). 

Although that's JavaScript and Jasmine 2.0 changed its async support going for a *done()* callback approach, I cannot stop to think how it looks really easy to switch from a sync to an async execution, especially if you look at its usage in CoffeeScript, that streamlines wrapping functions with functions: 

```coffescript
# preparation
beforeEach ->
  waitsForPromise ->
    atom.workspace.open 'c.coffee'
```

```coffescript
# expectation
it "should be opened in an editor", ->
  waitsForPromise ->
    atom.workspace.open('c.coffee').then (editor) ->
      expect(editor.getPath()).toContain 'c.coffee'
```

In C#, user would just keep setting the same hooks (e.g. before, beforeEach, it, ...) and when s/he has async preparation or expectation, just wrap that in some `waits()` provided by `nspec` instance. 
One issue I see here is that if user forgets to wrap an async execution, that will be recorded as a fire-and-forget run, and test would randomly fail or not. The framework would not be able to raise any error. But the same happens with current implementation if user assigns async lambda to `it` or `before`. 

Still thinking...

**Comment by amirrajan** [comment]
>One issue I see here is that if user forgets to wrap an async execution

Basically that ^. NodeJS is assumed async by default, so I think it's expected that you wrap. But I'm fine with either approach (don't do much async stuff in .net). So I'll defer to your wisdom :-)

**Comment by amirrajan** [comment]
Ensure that both the parts of the DSL start with `itX` ensures that `it` and `itAsync` will show up right next to each other.

**Comment by BrainCrumbz** [comment]
Yeah, between asyncXxx and xxxAsync, I'm now definitely for xxxAsync. Hence at least will change. Until change is made, I'll think about this wrapping approach too. At some point I thought about having both approaches in API, at the same time, but that seemed a little too confusing from the user point of view.

**Comment by amirrajan** [comment]
Totally up to you. You are now the async pro XD

**Comment by BrainCrumbz** [comment]
Ok, up to [this commit](https://github.com/mattflo/NSpec/commit/feb6d48611e772a3e1a8998693720c8007eb6d94) there are renamed async hooks and some minor tests that were missing. Would you like to give a go again with your test suite?

**Comment by amirrajan** [comment]
Will do! Gimme till Monday evening.

**Comment by amirrajan** [comment]
all is good \o/

**Comment by BrainCrumbz** [comment]
great! So finally we can move on with merge into default...

**Comment by BrainCrumbz** [comment]
I guess PR #90 can close this now. Should we open a new issue related to updating web pages as well?

**Comment by amirrajan** [comment]
Yep. I need to redo that damn website anyways.

**Comment by amirrajan** [comment]
I'll get a nuget package out this weekend. Unless you want a shot at doing that?

**Comment by BrainCrumbz** [comment]
Uhm. Never knew how to do that. What steps do you usually perform?

**Comment by amirrajan** [comment]
Just need to give you ownership to the nuget package. And then you can run `rake all` which updates the website and deploys the package. Just need your nuget username.

**Comment by BrainCrumbz** [comment]
`rake all` sounds like ruby's needed :) ... I guess I'll run this from a Mac (instead of Windows), if I'm not wrong that should be installed by default there.  
I'll post nuget username here as soon as I create one.

**Comment by BrainCrumbz** [comment]
Tried on Mac, got a bunch of errors about `build install`and missing libraries. I guess that `rake all`is also trying to build (again) the library ... that will not work on a Mac, right?

**Comment by amirrajan** [comment]
Yep.. only works on Windows right now. Have you been doing all your dev on Mac (pretty awesome if that's the case).

**Comment by BrainCrumbz** [comment]
No, not at all. I just thought about switching to Mac in order to build the website, as it was running on ruby. Then I realized that was trying to build DLL anyway and of course it was looking for Windows *stuff*.

**Comment by amirrajan** [comment]
I think we can close this one and start a new one for the `waits` approach. Close with mini retro?

1. Anything that can be improved in the code base to make it easier for new comers to jump in?
2. Stylistic concerns?
3. Any nitpick/feedback?

**Comment by amirrajan** [comment]
1.0.1:  http://www.nuget.org/packages/nspec/

**Comment by BrainCrumbz** [comment]
yay!
Re. retrospective:
Codebase looks very good and well-designed. Styles (e.g. no explicit `private` qualifier) seem to hold throughout whole codebase. If I have to think about possible improvements:

1. Unit test organization: sometimes it is not really clear why some tests are placed (or not) in a folder (e.g. `describe_RunningSpecs` or `describe_before_and_after`) or in test project root.
1. If you remember, one of the first things you had to explain was the main *gist* of this test framework, i.e. "the flow" through runner, context builder, context runner, etc. I don't remember if it's already like that, but it could be worth to put that up in some `contributing.md` page (so a little deeper than the actual section in readme)
1. Last one, very fresh :) : if (and if) this is mainly a .NET thing, it could be easier for contributors to have as much of build/deploy tooling as possible in NET, even better straight in VS. So e.g. have a VS project to build the NuGet package, instead of having to switch to ruby/ rake/ builder. Don't know if also the static website generation can be run from MSBuild/ VS.

All in all, I think it has been quite a good developing experience!

**Comment by BrainCrumbz** [comment]
Oops... one thing I forgot about naming: *class-level* and *method-level* - when looking at the code, not necessarily at the docs - somehow seem to get mixed up or overlap one each other. E.g. class-level context (shortly, class-context) Vs method-level before, although they both refer to the case of having test cases directly inside the class, and not inside a method.

**Comment by amirrajan** [comment]
:+1:

**Comment by jspringer2020** [comment]
Hey guys, I have [forked](https://github.com/mattflo/NSpec/compare/master...jspringer2020:feature/Expect_Async?expand=1) and update the issues with `expect<>` that I [mentioned](https://github.com/mattflo/NSpec/issues/83#issuecomment-125224912) with regards to `async` and `await`. Should I create an issue or just submit a pull request? There are some changes to how the exception is examined in the `nspec` class as well as several spec files.

**Comment by BrainCrumbz** [comment]
Don't know enough about the *best* way to proceed, maybe @amirrajan does. I guess creating a PR with a proper description, explaining its objectives, and a reference to the mentioned issue, is a good way to go,

**Comment by amirrajan** [comment]
@jspringer2020 pretty casual here, just create the pull request, and I'll do some testing as soon as I can. Any help you can provice @BrainCrumbz  would be greatly appreciated.
