### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by spupett** [mattflo/NSpec#85]
Is there a way to suppress warnings?  For instance, I have a few warnings saying NuGet packages were installed with a different framework.  I don't really care about that at the moment, but they really clutter the window that NSpec runs in.  Growler doesn't show them, but I like to see NSpec too.

**Comment by amirrajan** [comment]
We are currently working on updating NSpec to 4.5 (and updating the nuget package when that happens to get rid of the warning). What version of .Net/Visual Studio are you currently using?

**Comment by spupett** [comment]
I'm using a mix of 3.5 and 4.5 in VS 2013.

**Comment by amirrajan** [comment]
We're going to be upgraded NSpec to 4.5 (in the process of doing that now). Also, I'm thinking of releasing a nuget package that "installs" the source into the test project under an `/NSpec` directory. Thoughts on that?

**Comment by amirrajan** [comment]
4.5 version (1.0+) release.
