### ISSUE TITLE
Is describe_method_level_befores.cs actually testing method-level before?

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#87]
Maybe question title reads a little strange. Looking at [current `describe_method_level_befores` tests](https://github.com/mattflo/NSpec/blob/3d8c44a97bc1e2b409b918c0ccb933c30da7d367/NSpecSpecs/describe_RunningSpecs/describe_method_level_befores.cs#L19), is that actually setting a method-level before? Or is that just a *regular* context before?

```c#
void method_level_context()
{
    before = MethodLevelBefore;  // <---

    context["sub context"] = () => 
    {
        // ...
    };
}
```

**Background**: We were looking for unit tests on method-level befores and found those in `describe_method_level_befores`. *Doubling* them for the equivalent async version, tests passed basically without changing anything in `ClassContext.BuildMethodLevelBefore()` and that sounded strange. Maybe we're missing something from the big picture...

**Comment by BrainCrumbz** [comment]
Or, put it from another perspective:

`Context.BeforeInstance` is only set inside `ClassContext.BuildMethodLevelBefore()`. There's no unit test directly referring to `Context.BeforeInstance`, so the only pointer left is the naming. Judging by *BuildMethodLevelBefore*, one can infer that the related unit tests are to be found in `describe_method_level_befores.cs`. But there, only `Context.Before` is actually exercised. So we could not find unit tests for `BeforeInstance`, plus it seems that unit test class has a confusing name.

**Comment by amirrajan** [comment]
That does look like a weird test...

Try commenting out the line in the implementation (around here: https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/Context.cs#L13) and see what tests fail. I usually use that to figure out what tests cover which lines of code.

As for execution orders, take a look at this wiki entry: https://github.com/mattflo/NSpec/wiki/Execution-Orders

**Comment by BrainCrumbz** [comment]
thanks for reply. I think I'll give a look at execution order later. As of now, I cannot find a test that covers `Context.BeforeInstance`. If I comment out line 13, that would touch quite a number of tests I guess, but we're interested in BeforeInstance, which is on line 15. Maybe that is a deprecated API?

**Comment by BrainCrumbz** [comment]
Please have a look at [this commit](https://github.com/mattflo/NSpec/commit/9b7e022e08e4c95bea848490ebc74823b5c0869b), especially the following two files:

 1. [NSpecSpecs/describe_RunningSpecs/describe_method_level_befores.cs](https://github.com/mattflo/NSpec/blob/9b7e022e08e4c95bea848490ebc74823b5c0869b/NSpecSpecs/describe_RunningSpecs/describe_method_level_befores.cs) 

 1. [NSpecSpecs/describe_RunningSpecs/describe_async_method_level_befores.cs](https://github.com/mattflo/NSpec/blob/9b7e022e08e4c95bea848490ebc74823b5c0869b/NSpecSpecs/describe_RunningSpecs/describe_async_method_level_befores.cs)

That seems to me a way to actually try to test `before_each`, which it looks like are the *real* method-level before hooks. What do you think about it?

**Comment by amirrajan** [comment]
I'll take a look and try to figure out where the missing test is. Juggling a couple of things so it'll take my a couple of days.

I have a massive test suite here that I can run it through: https://github.com/amirrajan/Oak/tree/master/Oak.Tests

**Comment by amirrajan** [comment]
still an issue? /cc @BrainCrumbz

**Comment by BrainCrumbz** [comment]
Trying to recap:

(As it was)[https://github.com/mattflo/NSpec/blob/3d8c44a97bc1e2b409b918c0ccb933c30da7d367/NSpecSpecs/describe_RunningSpecs/describe_method_level_befores.cs#L19], I think that test was just verifying what happened on a *context*-level `before`, not on a *class*-level `before`. I did not get for sure if *method*-level before stands for the former or the latter, at the time we thought it should be the same as class-level.

Then that test has been changed in async branch and the [current version](https://github.com/mattflo/NSpec/blob/c881a3c26e0c9b4ea26042429ca4c1078baa9e10/NSpecSpecs/describe_RunningSpecs/describe_method_level_befores.cs#L56) tries at least to verify that the class-level `before` is not null, although is not able to verify that is actually set to the expected method.

Please have a look at the test file, and if it looks ok for you I suggest to close the issue as "solved". It'd be great to also understand for sure what we mean for *method*-level `before`.

**Comment by BrainCrumbz** [comment]
Up
