### ISSUE TITLE
Does this work in VS2015?

### ISSUE THREAD

**Issue by michaelgwelch** [mattflo/NSpec#89]
I'm following the Write Your First Spec guidance at http://nspec.org

and not much is going right.

1. This line doesn't compile `void before_each() { name = "NSpec"; }` There is no variable named `name`. I assume that's just a typo? Ok, I declare a field of type name to get everything to compile.
2. The DebuggerShim says that this allows use to use Resharper's test runner. However, Resharper does not see the nspec tests. The test runner launches but my tests don't show up in the tree.
3. The quick start guide says type `NSpecRunner.exe YourClassLibraryName\bin\debug\YourClassLibraryName.dll` in the package manager console. It responds with `NSpecRunner.exe : The term 'NSpecRunner.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.`
4. I'm actually creating a .net 4.5 assembly. Your quick start says "create a .net 3.5 or 4.0". So I changed mine to be a 4.0 just in case.

My question is, does NSpec work in VS 2015?

**Comment by michaelgwelch** [comment]
I'm using specwatchr successfully to run the tests. I assume the file name of the tests is important? I just copied your sample describe_FirstTest into the Class1.cs file that VS automatically creates. The test runner did not find the tests until I renamed it describe_FirstTest.

**Comment by michaelgwelch** [comment]
Hmm, what other "tricks" are needed so that a test is recognized as a test. I was able to successfully run your specwatchr example. However here is my small sample test program. When I save the file I get notified that `0 Examples, 0 Failed, 0 Pending`

I'm playing around with making things public, putting `spec` at the end of everything. I don't understand.

**Comment by michaelgwelch** [comment]
Ok, I figured it out. Looks like the class name and file name need to match exactly (even if the test class is actually in a different file. I found this out by accident as I copied one of your test class into the same file as my test class. It wasn't discovered. Until I create a new skeleton file that I was going to copy it into. As soon as that new file was created the class was discovered and run. Odd and unexpected behavior.

**Comment by BrainCrumbz** [comment]
When we initially approached to NSpec framework, we looked for some Visual Studio test runner. We found this [NSpec Test Adapter](https://visualstudiogallery.msdn.microsoft.com/7a52473f-9e1a-40f3-8bd8-6c00ab163609), which worked quite well. There was no need to give a particular name to test file, or test class or class under test.

Only later, when we had some (speed) issues with that adapter, we also tried:

1. Visual Studio [VSTest.Console.exe](https://msdn.microsoft.com/en-us/library/jj155796.aspx), that must be run from a VS Command Prompt and is somehow more clumsy
1. NSpecRunner, from a regular command prompt, which can be found at `Path\To\Your\Solution\packages\nspec.0.9.68\tools\NSpecRunner.exe`

HTH

**Comment by amirrajan** [comment]
The NSpec 1.0 recommendation will be to make your test project a console app as opposed to a class library, and add the following code to Program.cs:

```
var tagOrClassName = "class_or_tag_you_want_to_debug";

var types = GetType().Assembly.GetTypes(); 
// OR
// var types = new Type[]{typeof(Some_Type_Containg_some_Specs)};
var finder = new SpecFinder(types, "");
var builder = new ContextBuilder(finder, new Tags().Parse(tagOrClassName), new DefaultConventions());
var runner = new ContextRunner(builder, new ConsoleFormatter(), false);
var results = runner.Run(builder.Contexts().Build());

if(results.Failures().Count() > 0) return -1;
```

At this point, you can simply run/debug your console app and skip the whole rigamarole of trying to have a VS integrated runner (since your test suite is just a console app).

**Comment by amirrajan** [comment]
I know it feels weird to create a console app. But, I think it gives you the most freedom to extend as you see fit (and also keep things editor agnostic).  What do you guys think?

**Comment by michaelgwelch** [comment]
I think a console app is fine. It's easy to run, etc. For a 1.0 version completely acceptable. I would imagine some consumers of testing frameworks are used to their fancy gui windows and test runners and so you may want to pursue that in a future version.

**Comment by amirrajan** [comment]
Also. This is the essence of specwatchr if you want to role your own. Basically it s a loose hanging console app that watches for directory changes and runs rake tasks: https://gist.github.com/amirrajan/3879724

**Comment by amirrajan** [comment]
Here is a bit more "battle hardened" file watcher console app: https://github.com/amirrajan/Loam/blob/master/sidekickapp.cs

**Comment by amirrajan** [comment]
If you want to try the console app approach, here is a very succinct `Program.cs`:

```
using System.Linq;
using System.Reflection;
using NSpec;
using NSpec.Domain;
using NSpec.Domain.Formatters;
using System.IO;
using System;
using System.Diagnostics;


namespace MyTestProject.Tests
{
    class Program
    {
        static void Main(string[] args)
        {
            var ri = new RunnerInvocation(Assembly.GetExecutingAssembly().Location, "", false);
            ri.Run();
            
            Console.WriteLine("Done.");
            Console.ReadLine();
        }
    }
}
```
