### ISSUE TITLE
Conditions for running Context.RunBeforeAll vs Context.RunAfterAll

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#92]
In `Context.Run` method [here](https://github.com/mattflo/NSpec/blob/c881a3c26e0c9b4ea26042429ca4c1078baa9e10/NSpec/Domain/Context.cs#L192), at the beginning, `RunBeforeAll` method is ran only if: 

```
AllExamples().Any(e=>e.ShouldNotSkip(nspec.tagsFilter))
```

While, at the end, `RunAfterAll` method is ran only if a different, more permissive, condition holds:

```
AllExamples().Count() > 0  // same as AllExamples().Any()
```

Shouldn't those run only when same condition holds? Or else none of them should run at all.

**Comment by amirrajan** [comment]
Agreed.
