### ISSUE TITLE
Clean up old development or feature branches

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#97]
What do you guys think about cleaning up a bit the list of available branches? The idea is that only the branches that are still meaningful or needed would be found in the list. All the rest, if needed, would still be available under dedicated *archive* tags, which in turn are very well defined and easy to find.

For example that's what happend to previous branches `exceptions-after-before-all` and `async-least`: now in tags selector there are:

![tag-screenshot](https://cloud.githubusercontent.com/assets/3185573/11091272/1d363ac0-8879-11e5-981e-98f5c64c0ae8.png)

The steps to achieve that would be<sup>[1](#sources)</sup>:

```bash
git tag archive/<branch name> <branch name>
git branch -d <branch name>  # expect warning here
git push origin archive/<branch name>
git push origin --delete <branch name>
```
If one needs to *resume* one of such branches, the steps would be:

```bash
git checkout archive/<branch name>
git checkout -b <some branch name>
```

---

**Notes**

<a name="sources">1</a>: Steps were taken from a number of (StackOverflow) suggested solutions.

**Comment by amirrajan** [comment]
yep, kill them all

**Comment by BrainCrumbz** [comment]
Ok. 

Here's the list of archived and deleted branches until now [Work in Progress]:

```
after_all
autowebsite
beforeAll
comparableAsserts
failfast
focus
```

**Comment by BrainCrumbz** [comment]
Further branches archived:

```
liveconsole
nonunit
redefine_errors
seleniumbug
tags
tdnet
tooclever
```

@amirrajan don't know what to do with the following:

1. `gh-pages-rakefile`: this one seems unused, so maybe archive
1. `gh-pages-rewrite`: this one has recent activity, so probably it should be kept
1. `mono`: this one has recent activity, so probably it should be kept

What do you suggest?

**Comment by amirrajan** [comment]
keep `gh-pages-rewrite`, `mono` and `gh-pages-rakefil` stuff has been merged in :-)

And thanks man for cleaning this stuff up :-)

**Comment by BrainCrumbz** [comment]
You're welcome! So anyone wanting to contribute has a little easier time playing with branches.

So now also archived:

```
gh-pages-rakefile
mono
```

To quickly do this work we put up a simple Windows batch script. We thought it could be useful to store that for future cleaning. It might be a good idea to have the script under source control as well, and to insert a comment somewhere in contributing docs.

What do you think about creating a `/tools` (or maybe another name) directory under root to store that script? And then document it in [Contributing wiki page](https://github.com/mattflo/NSpec)?/wiki/Contributing

**Comment by amirrajan** [comment]
Probably just throw it into the README.md. I have a ruby binaries folder to make it easy for devs to get the right version of ruby and devkit installed.

Most of the ruby dependencies are because of the website creation which I'm planning to simplify and remove all need for ruby/rake and have that replaced with batch and shell scripts for getting everything built.

**Comment by BrainCrumbz** [comment]
Thanks for info. The script is in a `\scripts\` directory and it's described at the bottom in README.md. Do feel free to edit description or what else if needed.

I guess we can close this issue for now.
