### ISSUE TITLE
Docs: add example of data-driven test cases

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#99]
While reading [this post](https://booker.codes/data-driven-tests-in-javascript-using-mocha) on JS/Mocha, I remembered that we too had to find our way through creating some tests in a *data-driven fashion* with NSpec.

Of course this is not an issue with NSpec itself, instead it has to do with context/specification type of unit tests. Still, I guess an example on how to create data-driven tests with NSpec would make a good fit for a small section in readme or other documentation page.

What do you think? If you agree, we could put together a PR for that.

**Comment by amirrajan** [comment]
I'd just do this frankly: 


```
using NSpec;

class describe_PrimeFactors : nspec
{
    void when_determining_prime_factors()
    {
        new Each<int,int[]>
            {
            { 0, new int[] { } },
            { 1, new int[] { } },
            { 2, new[] { 2 } },
            { 3, new[] { 3 } },
            { 4, new[] { 2, 2 } },
            { 5, new[] { 5 } },
            { 6, new[] { 2, 3 } },
            { 7, new[] { 7 } },
            { 8, new[] { 2, 2, 2 } },
            { 9, new[] { 3, 3 } },
        }.Do((given, expected) =>
            it["{0} should be {1}".With(given, expected)] = () =>
                given.Primes().should_be(expected)
        );
    }
}
```

You can't do class level or method level, but it keeps things pretty simple.

**Comment by BrainCrumbz** [comment]
Now, where does those `Each<,>` and `Do()` come from?!? :)

This is just the kind of example we were looking for.

**Comment by amirrajan** [comment]
They are just random extension methods. It could be a for loop if you want it to be.
